
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.0.1.0
    2026 03 22 15:11:25
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="ahbl_to_axilite_bridge", LATTICE_IP_GENERATED="1" *) module ahbl_to_axilite_bridge (clk, 
        reset_n, 
        haddr_i, 
        hburst_i, 
        hmastlock_i, 
        hprot_i, 
        hready_i, 
        hsel_i, 
        hsize_i, 
        htrans_i, 
        hwdata_i, 
        hwrite_i, 
        hrdata_o, 
        hready_o, 
        hresp_o, 
        axi4_m_araddr_o, 
        axi4_m_arprot_o, 
        axi4_m_arready_i, 
        axi4_m_arvalid_o, 
        axi4_m_rready_o, 
        axi4_m_rvalid_i, 
        axi4_m_rdata_i, 
        axi4_m_rresp_i, 
        axi4_m_awaddr_o, 
        axi4_m_awprot_o, 
        axi4_m_awready_i, 
        axi4_m_awvalid_o, 
        axi4_m_wdata_o, 
        axi4_m_wstrb_o, 
        axi4_m_wready_i, 
        axi4_m_wvalid_o, 
        axi4_m_bresp_i, 
        axi4_m_bready_o, 
        axi4_m_bvalid_i) ;
    input clk ; 
    input reset_n ; 
    input [6:0] haddr_i ; 
    input [2:0] hburst_i ; 
    input hmastlock_i ; 
    input [3:0] hprot_i ; 
    input hready_i ; 
    input hsel_i ; 
    input [2:0] hsize_i ; 
    input [1:0] htrans_i ; 
    input [31:0] hwdata_i ; 
    input hwrite_i ; 
    output [31:0] hrdata_o ; 
    output hready_o ; 
    output hresp_o ; 
    output [4:0] axi4_m_araddr_o ; 
    output [2:0] axi4_m_arprot_o ; 
    input axi4_m_arready_i ; 
    output axi4_m_arvalid_o ; 
    output axi4_m_rready_o ; 
    input axi4_m_rvalid_i ; 
    input [31:0] axi4_m_rdata_i ; 
    input [1:0] axi4_m_rresp_i ; 
    output [4:0] axi4_m_awaddr_o ; 
    output [2:0] axi4_m_awprot_o ; 
    input axi4_m_awready_i ; 
    output axi4_m_awvalid_o ; 
    output [31:0] axi4_m_wdata_o ; 
    output [3:0] axi4_m_wstrb_o ; 
    input axi4_m_wready_i ; 
    output axi4_m_wvalid_o ; 
    input [1:0] axi4_m_bresp_i ; 
    output axi4_m_bready_o ; 
    input axi4_m_bvalid_i ; 
    ahbl_to_axilite_bridge_ipgen_ahbl_to_axi4lite_bridge #(.DATA_WIDTH_I(32),
            .AHBL_ADDR_WIDTH_I(7),
            .AXIL_ADDR_WIDTH_I(5)) ahbl_to_axi4lite_bridge_inst (.clk(clk), 
                .reset_n(reset_n), 
                .haddr_i(haddr_i[6:0]), 
                .hburst_i(hburst_i[2:0]), 
                .hmastlock_i(hmastlock_i), 
                .hprot_i(hprot_i[3:0]), 
                .hready_i(hready_i), 
                .hsel_i(hsel_i), 
                .hsize_i(hsize_i[2:0]), 
                .htrans_i(htrans_i[1:0]), 
                .hwdata_i(hwdata_i[31:0]), 
                .hwrite_i(hwrite_i), 
                .hrdata_o(hrdata_o[31:0]), 
                .hready_o(hready_o), 
                .hresp_o(hresp_o), 
                .axi4_m_araddr_o(axi4_m_araddr_o[4:0]), 
                .axi4_m_arprot_o(axi4_m_arprot_o[2:0]), 
                .axi4_m_arready_i(axi4_m_arready_i), 
                .axi4_m_arvalid_o(axi4_m_arvalid_o), 
                .axi4_m_rready_o(axi4_m_rready_o), 
                .axi4_m_rvalid_i(axi4_m_rvalid_i), 
                .axi4_m_rdata_i(axi4_m_rdata_i[31:0]), 
                .axi4_m_rresp_i(axi4_m_rresp_i[1:0]), 
                .axi4_m_awaddr_o(axi4_m_awaddr_o[4:0]), 
                .axi4_m_awprot_o(axi4_m_awprot_o[2:0]), 
                .axi4_m_awready_i(axi4_m_awready_i), 
                .axi4_m_awvalid_o(axi4_m_awvalid_o), 
                .axi4_m_wdata_o(axi4_m_wdata_o[31:0]), 
                .axi4_m_wstrb_o(axi4_m_wstrb_o[3:0]), 
                .axi4_m_wready_i(axi4_m_wready_i), 
                .axi4_m_wvalid_o(axi4_m_wvalid_o), 
                .axi4_m_bresp_i(axi4_m_bresp_i[1:0]), 
                .axi4_m_bready_o(axi4_m_bready_o), 
                .axi4_m_bvalid_i(axi4_m_bvalid_i)) ; 
endmodule



`timescale 1ns/100ps
// =============================================================================
//                           COPYRIGHT NOTICE
// Copyright 2024 (c) Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// This confidential and proprietary software may be used only as authorized by
// a licensing agreement from Lattice Semiconductor Corporation.
// The entire notice above must be reproduced on all authorized copies and
// copies may only be made to the extent permitted by a licensing agreement from
// Lattice Semiconductor Corporation.
//
// Lattice Semiconductor Corporation        TEL : 1-800-Lattice (USA and Canada)
// 5555 NE Moore Court                            408-826-6000 (other locations)
// Hillsboro, OR 97124                     web  : http://www.latticesemi.com/
// U.S.A                                   email: techsupport@lscc.com
// =============================================================================
//-F I L E D E T A I L S------------------------------------------------------
// Description : # This bridge module has 1 AXI4-Lite slave port and
//                 one AXI4-Lite master port. It connects simply
//                 slave signals to master signals and vice-versa #
//
//-----------------------------------------------------------------------------
//------------------------------//
// Timescale
//------------------------------//
//NOTE----------------------------
// prefix axi4_s_ : AXI4-Lite slave signals
// prefix axi4_m_ : AXI4-Lite master signals
module ahbl_to_axilite_bridge_ipgen_ahbl_to_axi4lite_bridge #(parameter DATA_WIDTH_I = 32, 
        parameter AHBL_ADDR_WIDTH_I = 32, 
        parameter AXIL_ADDR_WIDTH_I = 32) (
    input clk, 
    input reset_n, 
    // slave in
    // AHB-Lite signals
    input logic [(AHBL_ADDR_WIDTH_I - 1):0] haddr_i, 
    input logic [2:0] hburst_i, 
    input logic hmastlock_i,  //not used
    input logic [3:0] hprot_i,  //not used
    input logic hready_i, 
    input logic hsel_i, 
    input logic [2:0] hsize_i, 
    input logic [1:0] htrans_i, 
    input logic [(DATA_WIDTH_I - 1):0] hwdata_i, 
    input logic hwrite_i, 
    output logic [(DATA_WIDTH_I - 1):0] hrdata_o, 
    output logic hready_o, 
    output logic hresp_o, 
    // Master out
    output logic [(AXIL_ADDR_WIDTH_I - 1):0] axi4_m_araddr_o, 
    output logic [2:0] axi4_m_arprot_o, 
    input logic axi4_m_arready_i, 
    output logic axi4_m_arvalid_o, 
    output logic axi4_m_rready_o, 
    input logic axi4_m_rvalid_i, 
    input logic [(DATA_WIDTH_I - 1):0] axi4_m_rdata_i, 
    input logic [1:0] axi4_m_rresp_i, 
    output logic [(AXIL_ADDR_WIDTH_I - 1):0] axi4_m_awaddr_o, 
    output logic [2:0] axi4_m_awprot_o, 
    input logic axi4_m_awready_i, 
    output logic axi4_m_awvalid_o, 
    output logic [(DATA_WIDTH_I - 1):0] axi4_m_wdata_o, 
    output logic [((DATA_WIDTH_I / 8) - 1):0] axi4_m_wstrb_o, 
    input logic axi4_m_wready_i, 
    output logic axi4_m_wvalid_o, 
    input logic [1:0] axi4_m_bresp_i, 
    output logic axi4_m_bready_o, 
    input logic axi4_m_bvalid_i) ;
    // Local variable
    logic hwrite_pl ; // write pulse if hwrite_i is high and htrans is non sequential.
    logic hwrite_pl_f1 ; // write pulse if hwrite_i is high and htrans is non sequential.
    logic hread_pl ; // read pulse if hwrite_i is low and htrans is non sequential.
    logic hread_pl_f1 ; 
    logic hread_pl_f2 ; 
    logic hread_pl_f3 ; 
    logic ahb_rd_ready ; 
    // Local Parameter
    // simulation purpose
    localparam UD = 1 ; 
    assign hwrite_pl = (((hwrite_i & hsel_i) & hready_i) & ((htrans_i == 2'b10) | (htrans_i == 2'b11))) ; 
    assign hread_pl = ((((~hwrite_i) & hsel_i) & hready_i) & ((htrans_i == 2'b10) | (htrans_i == 2'b11))) ; 
    // AHB Response
    assign hresp_o = 1'b0 ; //always okay response
    // AXI4 Lite Write master address
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    axi4_m_awaddr_o <= #(UD)   1'h0 ;
                end
            else
                if (hwrite_pl) 
                    begin
                        axi4_m_awaddr_o <= #(UD)   (haddr_i[(AHBL_ADDR_WIDTH_I - 1):0] >> 2) ;// Byte offset addressing
                    end
        end
    // AXI4 Lite Read master address
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    axi4_m_araddr_o <= #(UD)   1'h0 ;
                end
            else
                if (hread_pl) 
                    begin
                        axi4_m_araddr_o <= #(UD)   (haddr_i[(AHBL_ADDR_WIDTH_I - 1):0] >> 2) ;// Byte offset addressing
                    end
        end
    //Avalon byte enable signals
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    axi4_m_wstrb_o <= #(UD)   1'h0 ;
                end
            else
                if (hwrite_pl) 
                    /*| hread_pl */
                    begin
                        case ({haddr_i[1:0],
                                hsize_i})
                        5'b00000 : 
                            axi4_m_wstrb_o <= #(UD)   4'b0001 ;
                        5'b01000 : 
                            axi4_m_wstrb_o <= #(UD)   4'b0010 ;
                        5'b10000 : 
                            axi4_m_wstrb_o <= #(UD)   4'b0100 ;
                        5'b11000 : 
                            axi4_m_wstrb_o <= #(UD)   4'b1000 ;
                        5'b00001 : 
                            axi4_m_wstrb_o <= #(UD)   4'b0011 ;
                        5'b10001 : 
                            axi4_m_wstrb_o <= #(UD)   4'b1100 ;
                        5'b00010 : 
                            axi4_m_wstrb_o <= #(UD)   4'b1111 ;
                        endcase 
                    end
        end
    // hready_o signal
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    hready_o <= #(UD)   1'b1 ;
                end
            else
                if ((hread_pl | hwrite_pl)) 
                    // High priority
                    begin
                        hready_o <= #(UD)   1'b0 ;
                    end
                else
                    //x  else if ( axi4_m_rvalid_i | axi4_m_bvalid_i )
                    // -------------------------------------------------------------------------------
                    // Q. Why added following axi4_m_arready_i dependency ?
                    // A. Earlier, read data was not available from the AXI Lite interface, 
                    //    so in such cases, any data available on the bus would be passed 
                    //    to the AHB Lite read data. Now, we are ensuring that the data 
                    //    is available from AXI Lite before passing it to the AHB Lite `hrdata_o`.
                    // -------------------------------------------------------------------------------
                    if ((axi4_m_arready_i | axi4_m_bvalid_i)) 
                        begin
                            hready_o <= #(UD)   1'b1 ;
                        end
        end
    // AXI4Lite read request
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    axi4_m_arvalid_o <= #(UD)   1'b0 ;
                end
            else
                if (hread_pl) 
                    // High priority
                    begin
                        axi4_m_arvalid_o <= #(UD)   1'b1 ;
                    end
                else
                    if (axi4_m_arready_i) 
                        begin
                            axi4_m_arvalid_o <= #(UD)   1'b0 ;
                        end
        end
    // AXI4Lite write request
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    axi4_m_awvalid_o <= #(UD)   1'b0 ;
                end
            else
                if (hwrite_pl) 
                    // High priority
                    begin
                        axi4_m_awvalid_o <= #(UD)   1'b1 ;
                    end
                else
                    if (axi4_m_awready_i) 
                        begin
                            axi4_m_awvalid_o <= #(UD)   1'b0 ;
                        end
        end
    // One clock delayed hwrite_pl
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    hwrite_pl_f1 <= #(UD)   '0 ;
                end
            else
                begin
                    hwrite_pl_f1 <= #(UD)   hwrite_pl ;
                end
        end
    // AXI4Lite write request
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    axi4_m_wvalid_o <= #(UD)   1'b0 ;
                end
            else
                if (hwrite_pl_f1) 
                    // High priority
                    begin
                        axi4_m_wvalid_o <= #(UD)   1'b1 ;
                    end
                else
                    if (axi4_m_wready_i) 
                        begin
                            axi4_m_wvalid_o <= #(UD)   1'b0 ;
                        end
        end
    // AXI4Lite write data
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    axi4_m_wdata_o <= #(UD)   '0 ;
                end
            else
                if (hwrite_pl_f1) 
                    begin
                        axi4_m_wdata_o <= #(UD)   hwdata_i ;
                    end
        end
    // AHBLite Read Data
    //  always_ff @ ( posedge clk or negedge reset_n )
    //    begin
    //      if ( ~reset_n )
    //        begin
    //          hrdata_o <= #UD '0;
    //        end
    //      else if ( axi4_m_rvalid_i )
    //        begin
    //          hrdata_o <= #UD axi4_m_rdata_i;
    //        end
    //    end
    assign hrdata_o = (axi4_m_rvalid_i ? axi4_m_rdata_i : '0) ; 
    // flop
    always_ff
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    hread_pl_f1 <= #(UD)   '0 ;
                    hread_pl_f2 <= #(UD)   '0 ;
                    hread_pl_f3 <= #(UD)   '0 ;
                end
            else
                begin
                    hread_pl_f1 <= #(UD)   hread_pl ;
                    hread_pl_f2 <= #(UD)   hread_pl_f1 ;
                    hread_pl_f3 <= #(UD)   hread_pl_f2 ;
                end
        end
    // We are waiting for the read operation on the AXI lite bus.  
    assign ahb_rd_ready = (~(((hread_pl | hread_pl_f1) | hread_pl_f2) | hread_pl_f3)) ; 
    //Fixed Values for unused AXI4Lite signals.
    assign axi4_m_arprot_o = '0 ; 
    assign axi4_m_awprot_o = '0 ; 
    assign axi4_m_bready_o = '1 ; 
    assign axi4_m_rready_o = '1 ; 
endmodule


