/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.0.1.0
    2026 03 22 15:11:25
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module ahbl_to_axilite_bridge (clk, reset_n, haddr_i, hburst_i, hmastlock_i,
    hprot_i, hready_i, hsel_i, hsize_i, htrans_i, hwdata_i, hwrite_i, hrdata_o,
    hready_o, hresp_o, axi4_m_araddr_o, axi4_m_arprot_o, axi4_m_arready_i,
    axi4_m_arvalid_o, axi4_m_rready_o, axi4_m_rvalid_i, axi4_m_rdata_i,
    axi4_m_rresp_i, axi4_m_awaddr_o, axi4_m_awprot_o, axi4_m_awready_i,
    axi4_m_awvalid_o, axi4_m_wdata_o, axi4_m_wstrb_o, axi4_m_wready_i,
    axi4_m_wvalid_o, axi4_m_bresp_i, axi4_m_bready_o, axi4_m_bvalid_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  reset_n;
    input  [6:0]  haddr_i;
    input  [2:0]  hburst_i;
    input  hmastlock_i;
    input  [3:0]  hprot_i;
    input  hready_i;
    input  hsel_i;
    input  [2:0]  hsize_i;
    input  [1:0]  htrans_i;
    input  [31:0]  hwdata_i;
    input  hwrite_i;
    output  [31:0]  hrdata_o;
    output  hready_o;
    output  hresp_o;
    output  [4:0]  axi4_m_araddr_o;
    output  [2:0]  axi4_m_arprot_o;
    input  axi4_m_arready_i;
    output  axi4_m_arvalid_o;
    output  axi4_m_rready_o;
    input  axi4_m_rvalid_i;
    input  [31:0]  axi4_m_rdata_i;
    input  [1:0]  axi4_m_rresp_i;
    output  [4:0]  axi4_m_awaddr_o;
    output  [2:0]  axi4_m_awprot_o;
    input  axi4_m_awready_i;
    output  axi4_m_awvalid_o;
    output  [31:0]  axi4_m_wdata_o;
    output  [3:0]  axi4_m_wstrb_o;
    input  axi4_m_wready_i;
    output  axi4_m_wvalid_o;
    input  [1:0]  axi4_m_bresp_i;
    output  axi4_m_bready_o;
    input  axi4_m_bvalid_i;
endmodule