/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.3.1.01
    2026 04 13 09:51:33
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module isp_ccm (axis_rx_clk_i, axis_rx_arstn_i, axis_tx_clk_i, axis_tx_arstn_i,
    rx_tdata_i, rx_tuser_i, rx_tlast_i, rx_tvalid_i, rx_tready_o, tx_tready_i,
    tx_tdata_o, tx_tvalid_o, tx_tlast_o, tx_tuser_o, axi_lite_clk_i,
    axi_lite_rst_n_i, aw_valid_i, aw_address_i, aw_ready_o, w_valid_i,
    w_data_i, w_strb_i, w_ready_o, b_valid_o, b_response_o, b_ready_i,
    ar_valid_i, ar_address_i, ar_ready_o, r_data_o, r_valid_o, r_response_o,
    r_ready_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  axis_rx_clk_i;
    input  axis_rx_arstn_i;
    input  axis_tx_clk_i;
    input  axis_tx_arstn_i;
    input  [47:0]  rx_tdata_i;
    input  [1:0]  rx_tuser_i;
    input  rx_tlast_i;
    input  rx_tvalid_i;
    output  rx_tready_o;
    input  tx_tready_i;
    output  [47:0]  tx_tdata_o;
    output  tx_tvalid_o;
    output  tx_tlast_o;
    output  [1:0]  tx_tuser_o;
    input  axi_lite_clk_i;
    input  axi_lite_rst_n_i;
    input  aw_valid_i;
    input  [4:0]  aw_address_i;
    output  aw_ready_o;
    input  w_valid_i;
    input  [31:0]  w_data_i;
    input  [3:0]  w_strb_i;
    output  w_ready_o;
    output  b_valid_o;
    output  [1:0]  b_response_o;
    input  b_ready_i;
    input  ar_valid_i;
    input  [4:0]  ar_address_i;
    output  ar_ready_o;
    output  [31:0]  r_data_o;
    output  r_valid_o;
    output  [1:0]  r_response_o;
    input  r_ready_i;
endmodule