/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.4.0.0
    2026 02 28 19:29:36
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module ahbl_to_lmmi_inst (ahbl_clk, ahbl_reset_n, ahbls_c_hburst_i,
    ahbls_c_hmastlock_i, ahbls_c_hprot_i, ahbls_c_hready_i, ahbls_c_hsel_i,
    ahbls_c_haddr_i, ahbls_c_hwrite_i, ahbls_c_hwdata_i, ahbls_c_hsize_i,
    ahbls_c_htrans_i, ahbls_c_hrdata_o, ahbls_c_hready_o, ahbls_c_hresp_o,
    lm_clk_i, lm_reset_n_i, lmmi_rdata_i, lmmi_rdata_valid_i, lmmi_ready_i,
    lmmi_request_o, lmmi_wr_rdn_o, lmmi_offset_o, lmmi_wdata_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  ahbl_clk;
    input  ahbl_reset_n;
    input  [2:0]  ahbls_c_hburst_i;
    input  ahbls_c_hmastlock_i;
    input  [3:0]  ahbls_c_hprot_i;
    input  ahbls_c_hready_i;
    input  ahbls_c_hsel_i;
    input  [16:0]  ahbls_c_haddr_i;
    input  ahbls_c_hwrite_i;
    input  [31:0]  ahbls_c_hwdata_i;
    input  [2:0]  ahbls_c_hsize_i;
    input  [1:0]  ahbls_c_htrans_i;
    output  [31:0]  ahbls_c_hrdata_o;
    output  ahbls_c_hready_o;
    output  ahbls_c_hresp_o;
    input  lm_clk_i;
    input  lm_reset_n_i;
    input  [31:0]  lmmi_rdata_i;
    input  lmmi_rdata_valid_i;
    input  lmmi_ready_i;
    output  lmmi_request_o;
    output  lmmi_wr_rdn_o;
    output  [14:0]  lmmi_offset_o;
    output  [31:0]  lmmi_wdata_o;
endmodule