
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.4.0.0
    2026 02 28 19:29:36
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="ahbl_to_lmmi_inst", LATTICE_IP_GENERATED="1" *) module ahbl_to_lmmi_inst (ahbl_clk, 
        ahbl_reset_n, 
        ahbls_c_hburst_i, 
        ahbls_c_hmastlock_i, 
        ahbls_c_hprot_i, 
        ahbls_c_hready_i, 
        ahbls_c_hsel_i, 
        ahbls_c_haddr_i, 
        ahbls_c_hwrite_i, 
        ahbls_c_hwdata_i, 
        ahbls_c_hsize_i, 
        ahbls_c_htrans_i, 
        ahbls_c_hrdata_o, 
        ahbls_c_hready_o, 
        ahbls_c_hresp_o, 
        lm_clk_i, 
        lm_reset_n_i, 
        lmmi_rdata_i, 
        lmmi_rdata_valid_i, 
        lmmi_ready_i, 
        lmmi_request_o, 
        lmmi_wr_rdn_o, 
        lmmi_offset_o, 
        lmmi_wdata_o) ;
    input ahbl_clk ; 
    input ahbl_reset_n ; 
    input [2:0] ahbls_c_hburst_i ; 
    input ahbls_c_hmastlock_i ; 
    input [3:0] ahbls_c_hprot_i ; 
    input ahbls_c_hready_i ; 
    input ahbls_c_hsel_i ; 
    input [16:0] ahbls_c_haddr_i ; 
    input ahbls_c_hwrite_i ; 
    input [31:0] ahbls_c_hwdata_i ; 
    input [2:0] ahbls_c_hsize_i ; 
    input [1:0] ahbls_c_htrans_i ; 
    output [31:0] ahbls_c_hrdata_o ; 
    output ahbls_c_hready_o ; 
    output ahbls_c_hresp_o ; 
    input lm_clk_i ; 
    input lm_reset_n_i ; 
    input [31:0] lmmi_rdata_i ; 
    input lmmi_rdata_valid_i ; 
    input lmmi_ready_i ; 
    output lmmi_request_o ; 
    output lmmi_wr_rdn_o ; 
    output [14:0] lmmi_offset_o ; 
    output [31:0] lmmi_wdata_o ; 
    ahbl_to_lmmi_inst_ipgen_ahbl_to_lmmi_bridge #(.UD(1),
            .ADDR_WIDTH_I(17),
            .DATA_WIDTH_I(32),
            .BYTE_EN_WIDTH(4)) ahbl_to_lmmi_bridge_inst (.ahbl_clk(ahbl_clk), 
                .ahbl_reset_n(ahbl_reset_n), 
                .ahbls_c_hburst_i(ahbls_c_hburst_i[2:0]), 
                .ahbls_c_hmastlock_i(ahbls_c_hmastlock_i), 
                .ahbls_c_hprot_i(ahbls_c_hprot_i[3:0]), 
                .ahbls_c_hready_i(ahbls_c_hready_i), 
                .ahbls_c_hsel_i(ahbls_c_hsel_i), 
                .ahbls_c_haddr_i(ahbls_c_haddr_i[16:0]), 
                .ahbls_c_hwrite_i(ahbls_c_hwrite_i), 
                .ahbls_c_hwdata_i(ahbls_c_hwdata_i[31:0]), 
                .ahbls_c_hsize_i(ahbls_c_hsize_i[2:0]), 
                .ahbls_c_htrans_i(ahbls_c_htrans_i[1:0]), 
                .ahbls_c_hrdata_o(ahbls_c_hrdata_o[31:0]), 
                .ahbls_c_hready_o(ahbls_c_hready_o), 
                .ahbls_c_hresp_o(ahbls_c_hresp_o), 
                .lm_clk_i(lm_clk_i), 
                .lm_reset_n_i(lm_reset_n_i), 
                .lmmi_rdata_i(lmmi_rdata_i[31:0]), 
                .lmmi_rdata_valid_i(lmmi_rdata_valid_i), 
                .lmmi_ready_i(lmmi_ready_i), 
                .lmmi_request_o(lmmi_request_o), 
                .lmmi_wr_rdn_o(lmmi_wr_rdn_o), 
                .lmmi_offset_o(lmmi_offset_o[14:0]), 
                .lmmi_wdata_o(lmmi_wdata_o[31:0])) ; 
endmodule



`timescale 1ns/100ps
// =============================================================================
//                           COPYRIGHT NOTICE
// Copyright 2024 (c) Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// This confidential and proprietary software may be used only as authorized by
// a licensing agreement from Lattice Semiconductor Corporation.
// The entire notice above must be reproduced on all authorized copies and
// copies may only be made to the extent permitted by a licensing agreement from
// Lattice Semiconductor Corporation.
//
// Lattice Semiconductor Corporation        TEL : 1-800-Lattice (USA and Canada)
// 5555 NE Moore Court                            408-826-6000 (other locations)
// Hillsboro, OR 97124                     web  : http://www.latticesemi.com/
// U.S.A                                   email: techsupport@lscc.com
// =============================================================================
//-F I L E D E T A I L S-------------------------------------------------------
// Description  : This is top module of MCP Formulation Technique. It instances
//                two modules "sync_mcp_fdbk" and "sync_mcp_ack_fdbk".
//
//-----------------------------------------------------------------------------
//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
//
// Limitations of this method - Multi Cycle Path Formulation Technique:
//
//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
//
// -> This method is used only for single Read/Write operation. We can't use it
//    for the Burst Operations.
//
// -> So, we can use it for Register read/write.
//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
//
//  Reference Document:
//
//  Clock Domain Crossing (CDC) Design & Verification Techniques Using
//  SystemVerilog by Clifford E. Cummings ( page - 24 ).
//
//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
module ahbl_to_lmmi_inst_ipgen_ahbl_to_lmmi_bridge #(parameter UD = 1, 
        parameter ADDR_WIDTH_I = 19, 
        parameter DATA_WIDTH_I = 32, 
        parameter BYTE_EN_WIDTH = (DATA_WIDTH_I / 8)) (
    //===================================================
    //
    // Parameter Declaration
    //
    //===================================================
    // Unit delay parameter for Simulation purpose.
    // Avalon Control port address width parameter
    // Avalon Control port data width parameter
    // Byte enable width parameter
    input ahbl_clk,  // ahb clock
    input ahbl_reset_n,  // reset signal synchronized to "clk"
    input [2:0] ahbls_c_hburst_i,  //not used
    input ahbls_c_hmastlock_i,  //not used
    input [3:0] ahbls_c_hprot_i,  //not used
    input ahbls_c_hready_i,  // AHB Lite ready coming from multiplexor
    input ahbls_c_hsel_i,  // AHB Lite slave select coming from decoder
    input [(ADDR_WIDTH_I - 1):0] ahbls_c_haddr_i,  // ahb address
    input ahbls_c_hwrite_i,  // ahb write/read request
    input [(DATA_WIDTH_I - 1):0] ahbls_c_hwdata_i,  // ahb write data
    input [2:0] ahbls_c_hsize_i,  // ahb size of transfer
    input [1:0] ahbls_c_htrans_i,  // transfer type
    output logic [(DATA_WIDTH_I - 1):0] ahbls_c_hrdata_o,  // ahb read data
    output logic ahbls_c_hready_o,  // ahb slave ready
    (* syn_preserve=1 *) output logic ahbls_c_hresp_o,  // ahb slave response
    // LMMI Interface
    input lm_clk_i,  // lmmi clk
    input lm_reset_n_i,  // Synchronised Reset comes from external source.
    input [(DATA_WIDTH_I - 1):0] lmmi_rdata_i, 
    input lmmi_rdata_valid_i, 
    input lmmi_ready_i, 
    output logic lmmi_request_o, 
    output logic lmmi_wr_rdn_o, 
    // We are shift the AHBL offset to right shift by
    // two so address width decreased by 3.
    output logic [(ADDR_WIDTH_I - 3):0] lmmi_offset_o, 
    output logic [(DATA_WIDTH_I - 1):0] lmmi_wdata_o) ;
    //===================================================
    //
    // reg and wire declaration
    //
    //===================================================
    wire ahb_wr_ready_pl ; 
    wire ahb_rd_ready_pl ; 
    wire ahb_wr_req_pe ; 
    wire ahb_rd_req_pe ; 
    reg ready_to_accept_request ; 
    reg ahb_wr_req_pe_f1 ; 
    reg ahb_rd_req_pe_f1 ; 
    wire lmmi_rd_req_pl ; 
    wire lmmi_wr_req_pl ; 
    logic lmmi_wr_req_ack_pl ; 
    logic [(DATA_WIDTH_I - 1):0] lmmi_rd_data ; 
    logic [(ADDR_WIDTH_I - 1):0] ac_targeted_addr_8 ; 
    logic [10:0] rdy_counter ; 
    logic rd_req_timeout_pl ; 
    logic lmmi_req_int ; 
    logic lmmi_wr_rdn_int ; 
    //====================================================================
    //
    // -> Generating the pulse based on positive edge of write request
    //    and read request so that this pulse will be synchronized in
    //    ulpi clock domain.
    // -> Based on this synchronized pulse address, byte enable and data
    //    will be sampled.
    //=====================================================================
    // Note_1:
    // How have we used HREADY here?
    // Kindly refer Table 2-4 Decoder signals from AHB-Lite specification.
    // It states, "Each AHB-Lite slave has its own slave select signal HSELx and
    // this signal indicates that the current transfer is intended for the selected
    // slave. When the slave is initially selected, it must also monitor the
    // status of HREADY (coming from multiplexor) to ensure that the previous bus
    // transfer has been completed, before it responds to the current transfer.
    always
        @(posedge ahbl_clk or 
            negedge ahbl_reset_n)
        begin
            if ((~ahbl_reset_n)) 
                begin
                    ready_to_accept_request <= #(UD)   1'b1 ;
                end
            else
                if ((((ahbls_c_hsel_i & ahbls_c_hready_i) & ready_to_accept_request) & (ahbls_c_htrans_i == 2'b10))) 
                    begin
                        ready_to_accept_request <= #(UD)   1'b0 ;
                    end
                else
                    if (((ahb_wr_ready_pl || ahb_rd_ready_pl) || rd_req_timeout_pl)) 
                        begin
                            ready_to_accept_request <= #(UD)   1'b1 ;
                        end
        end
    // Please refer Note_1.
    //Positive edge of AHB Master write request
    assign ahb_wr_req_pe = ((((ahbls_c_hwrite_i & ahbls_c_hsel_i) & ahbls_c_hready_i) & ready_to_accept_request) & (ahbls_c_htrans_i == 2'b10)) ; 
    //Positive edge of AHB Master Read request
    assign ahb_rd_req_pe = (((((~ahbls_c_hwrite_i) & ahbls_c_hsel_i) & ahbls_c_hready_i) & ready_to_accept_request) & (ahbls_c_htrans_i == 2'b10)) ; 
    always
        @(posedge ahbl_clk or 
            negedge ahbl_reset_n)
        begin
            if ((~ahbl_reset_n)) 
                begin
                    ahb_wr_req_pe_f1 <= #(UD)   1'b0 ;
                end
            else
                begin
                    ahb_wr_req_pe_f1 <= #(UD)   ahb_wr_req_pe ;
                end
        end
    always
        @(posedge ahbl_clk or 
            negedge ahbl_reset_n)
        begin
            if ((~ahbl_reset_n)) 
                begin
                    ahb_rd_req_pe_f1 <= #(UD)   1'b0 ;
                end
            else
                begin
                    ahb_rd_req_pe_f1 <= #(UD)   ahb_rd_req_pe ;
                end
        end
    //===========================================================================
    //
    // Instantiate the "sync_mcp_fdbk" module for generating write request
    // in LMMI clock domain
    //
    //===========================================================================
    ahbl_to_lmmi_inst_ipgen_sync_mcp_ack_fdbk sync_mcp_ack_fdbk_wr (// sending clock domain signals
            .inclk(ahbl_clk), 
                .inclk_reset_n(ahbl_reset_n), 
                .indata_send_pl_i(ahb_wr_req_pe_f1), 
                .inclk_ack_pl_o(ahb_wr_ready_pl),  // ACK (read data valid) pulse from synchronizer.
            // receiving clock domain signals
            .outclk(lm_clk_i), 
                .outclk_reset_n(lm_reset_n_i), 
                .outclk_data_ld_i(lmmi_wr_req_ack_pl), 
                .outdata_ld_pl_o(lmmi_wr_req_pl) // read request pulse synchronized with "lm_clk_i"
            ) ; 
    //===========================================================================
    //
    // Instantiate the "sync_mcp_ack_fdbk" module for generating read request
    // in LMMI clock domain
    //
    //===========================================================================
    ahbl_to_lmmi_inst_ipgen_sync_mcp_ack_fdbk sync_mcp_ack_fdbk_rd (// sending clock domain signals
            .inclk(ahbl_clk), 
                .inclk_reset_n(ahbl_reset_n), 
                .indata_send_pl_i(ahb_rd_req_pe_f1), 
                .inclk_ack_pl_o(ahb_rd_ready_pl),  // ACK (read data valid) pulse from synchronizer.
            // receiving clock domain signals
            .outclk(lm_clk_i), 
                .outclk_reset_n(lm_reset_n_i), 
                .outclk_data_ld_i(lmmi_rdata_valid_i), 
                .outdata_ld_pl_o(lmmi_rd_req_pl) // read request pulse synchronized with "lm_clk_i"
            ) ; 
    // LMMI Request Internal
    // We would like to generate request to LMMI slave when it is ready.
    // When slave is ready, it asserts LMMI ready signal.
    // This is a local variable to store request received from AHB Lite domain.
    // Using this, we will generate external LMMI request.
    // Set this when we receive request from AHB Lite domain.
    // Reset this when LMMI slave has accepted our request.
    always
        @(posedge lm_clk_i or 
            negedge lm_reset_n_i)
        begin
            if ((~lm_reset_n_i)) 
                begin
                    lmmi_req_int <= #(UD)   1'b0 ;
                end
            else
                if ((lmmi_wr_req_pl | lmmi_rd_req_pl)) 
                    // Priority matters here!
                    begin
                        lmmi_req_int <= #(UD)   1'b1 ;
                    end
                else
                    if (lmmi_ready_i) 
                        begin
                            lmmi_req_int <= #(UD)   1'b0 ;
                        end
        end// always @ ( posedge lm_clk_i or negedge lm_reset_n_i )
    // LMMI Request External
    // Set this when we interla LMMI reqest is high and we get ready
    // signal from LMMI slave. This is to ensure we generate new request only
    // when slave is ready to accept that.
    // Reset this when LMMI slave has accepted our request.
    always
        @(posedge lm_clk_i or 
            negedge lm_reset_n_i)
        begin
            if ((~lm_reset_n_i)) 
                begin
                    lmmi_request_o <= #(UD)   1'b0 ;
                end
            else
                if ((lmmi_req_int & lmmi_ready_i)) 
                    // Priority matters here!
                    begin
                        lmmi_request_o <= #(UD)   1'b1 ;
                    end
                else
                    if (lmmi_ready_i) 
                        begin
                            lmmi_request_o <= #(UD)   1'b0 ;
                        end
        end// always @ ( posedge lm_clk_i or negedge lm_reset_n_i )
    // LMMI Write/Read selector (Internal)
    // 1 - Write
    // 0 - Read
    always
        @(posedge lm_clk_i or 
            negedge lm_reset_n_i)
        begin
            if ((~lm_reset_n_i)) 
                begin
                    lmmi_wr_rdn_int <= #(UD)   1'b0 ;
                end
            else
                begin
                    case ({lmmi_wr_req_pl,
                            lmmi_rd_req_pl})
                    2'b10 : 
                        // Write Request
                        begin
                            lmmi_wr_rdn_int <= #(UD)   1'b1 ;
                        end
                    2'b01 : 
                        // Read request
                        begin
                            lmmi_wr_rdn_int <= #(UD)   1'b0 ;
                        end
                    2'b11 : 
                        // This is never expected to happen.
                        // From AHB Lite, only either read or write can be started
                        // any time. Both can not start at the same time.
                        begin
                            // Retain value.
                            lmmi_wr_rdn_int <= #(UD)   lmmi_wr_rdn_int ;
                        end
                    2'b00 : 
                        // Retain value.
                        begin
                            lmmi_wr_rdn_int <= #(UD)   lmmi_wr_rdn_int ;
                        end
                    endcase // case ( {...
                end// else: !if( ~lm_reset_n_i )
        end// always @ ( posedge lm_clk_i or negedge lm_reset_n_i )
    // LMMI Write/Read selector
    // 1 - Write
    // 0 - Read
    always
        @(posedge lm_clk_i or 
            negedge lm_reset_n_i)
        begin
            if ((~lm_reset_n_i)) 
                begin
                    lmmi_wr_rdn_o <= #(UD)   1'b0 ;
                end
            else
                if ((lmmi_req_int & lmmi_ready_i)) 
                    begin
                        lmmi_wr_rdn_o <= #(UD)   lmmi_wr_rdn_int ;
                    end
        end
    // LMMI write request acknowledgement pulse
    // This will be generated when LMMI write request is high and slave asserts
    // LMMI ready. It indicates slave has accepted write request.
    always
        @(posedge lm_clk_i or 
            negedge lm_reset_n_i)
        begin
            if ((~lm_reset_n_i)) 
                begin
                    lmmi_wr_req_ack_pl <= #(UD)   1'b0 ;
                end
            else
                begin
                    lmmi_wr_req_ack_pl <= #(UD)   ((lmmi_request_o & lmmi_ready_i) & lmmi_wr_rdn_o) ;
                end
        end// always @ ( posedge lm_clk_i or negedge lm_reset_n_i )
    // Write data
    // We will save data available on AHB Lite bus when LMMI Write request pulse
    // is asserted.
    // We would not have released AHB Lite ready and hence we are sure valid write
    // data will be there on bus at the time we save it.
    always
        @(posedge lm_clk_i or 
            negedge lm_reset_n_i)
        begin
            if ((~lm_reset_n_i)) 
                begin
                    lmmi_wdata_o <= #(UD)   '0 ;
                end
            else
                if ((lmmi_req_int & lmmi_ready_i)) 
                    begin
                        lmmi_wdata_o <= #(UD)   ahbls_c_hwdata_i ;
                    end
        end// always @ ( posedge lm_clk_i or negedge lm_reset_n_i )
    // LMMI offset
    // This is in terms of word offset. At present, we have considered this as
    // 32 bits offset and hence used right shift operator to get 32 bits offset
    // from 8 bits offset.
    // We will save this when either LMMI write request or LMMI read request
    // pulse is asserted. We are sure that at that time, ac_targeted_addr_8
    // would be stable enough. This is because lmmi_wr_req_pl and lmmi_rd_req_pl
    // are passed through pulse synchronizer.
    always
        @(posedge lm_clk_i or 
            negedge lm_reset_n_i)
        begin
            if ((~lm_reset_n_i)) 
                begin
                    lmmi_offset_o <= #(UD)   '0 ;
                end
            else
                if ((lmmi_req_int & lmmi_ready_i)) 
                    begin
                        lmmi_offset_o <= #(UD)   (ac_targeted_addr_8 >> 2) ;
                    end
        end// always @ ( posedge lm_clk_i or negedge lm_reset_n_i )
    //==================================================================================
    //
    // -> Generating LMMI domain signals which are synchronized with "lm_clk_i".
    // -> Here we have not synchronized the multi bit data because they are synchronized
    //    on the bases of single bit pulse "write/read request"
    // -> Slave will sample these signals once it receives the synchronized pulse
    //    "lmmi_wr_req_pl" and "lmmi_rd_req_pl".
    //
    //==================================================================================
    // hold current address
    // Targeted address (byte offset)
    // We will save address from AHB Lite bus when we are ready to accept request.
    // ac_ prefix indicates this is synchronized to AHB Lite clock.
    always
        @(posedge ahbl_clk or 
            negedge ahbl_reset_n)
        begin
            if ((~ahbl_reset_n)) 
                begin
                    ac_targeted_addr_8 <= #(UD)   '0 ;
                end
            else
                if (ready_to_accept_request) 
                    begin
                        ac_targeted_addr_8 <= #(UD)   ahbls_c_haddr_i ;
                    end
        end// always @ ( posedge ahbl_clk or negedge ahbl_reset_n )
    // LMMI read data
    // we Need to latch the read data till hready_out goes high.
    always
        @(posedge lm_clk_i or 
            negedge lm_reset_n_i)
        begin
            if ((~lm_reset_n_i)) 
                begin
                    lmmi_rd_data <= #(UD)   '0 ;
                end
            else
                if (lmmi_rdata_valid_i) 
                    begin
                        lmmi_rd_data <= #(UD)   lmmi_rdata_i ;
                    end
        end
    // AHBL read data
    assign ahbls_c_hrdata_o = lmmi_rd_data ; 
    //Response signal
    // assign ahbls_c_hresp_o = 1'b0;  //always okay response
    always
        @(posedge ahbl_clk or 
            negedge ahbl_reset_n)
        begin
            if ((~ahbl_reset_n)) 
                begin
                    ahbls_c_hresp_o <= #(UD)   1'b0 ;// Okay
                end
            else
                if ((ahb_wr_req_pe || ahb_rd_req_pe)) 
                    begin
                        ahbls_c_hresp_o <= #(UD)   1'b0 ;// Okay response
                    end
                else
                    if (rd_req_timeout_pl) 
                        begin
                            ahbls_c_hresp_o <= #(UD)   1'b1 ;// Not okay response
                        end
        end// always @ ( posedge ahbl_clk or negedge ahbl_reset_n )
    //==================================================================================
    //
    // Idea for generating ready ("ahbls_c_hready_o") signal.
    //
    // -> On reset it will be HIGH.
    // -> When Master wants to perform any transfer, we will de-assert it
    // -> Once Slave is ready to provide asked data,
    //    we are asserting it.
    //
    //==================================================================================
    always
        @(posedge ahbl_clk or 
            negedge ahbl_reset_n)
        begin
            if ((~ahbl_reset_n)) 
                begin
                    ahbls_c_hready_o <= #(UD)   1'b1 ;
                end
            else
                if ((ahb_wr_req_pe || ahb_rd_req_pe)) 
                    begin
                        ahbls_c_hready_o <= #(UD)   1'b0 ;
                    end
                else
                    if (((ahb_wr_ready_pl || ahb_rd_ready_pl) || rd_req_timeout_pl)) 
                        begin
                            ahbls_c_hready_o <= #(UD)   1'b1 ;
                        end
        end// always @ ( posedge ahbl_clk or negedge ahbl_reset_n )
    // Ready Counter
    always
        @(posedge ahbl_clk or 
            negedge ahbl_reset_n)
        begin
            if ((~ahbl_reset_n)) 
                begin
                    rdy_counter <= #(UD)   '0 ;
                end
            else
                if (ahbls_c_hready_o) 
                    begin
                        rdy_counter <= #(UD)   '0 ;
                    end
                else
                    begin
                        rdy_counter <= #(UD)   (rdy_counter + 1'b1) ;
                    end
        end// always @ ( posedge ahbl_clk or negedge ahbl_reset_n )
    always
        @(posedge ahbl_clk or 
            negedge ahbl_reset_n)
        begin
            if ((~ahbl_reset_n)) 
                begin
                    rd_req_timeout_pl <= #(UD)   1'b0 ;
                end
            else
                begin
                    rd_req_timeout_pl <= #(UD)   (rdy_counter == 11'd500) ;
                end
        end// always @ ( posedge ahbl_clk or negedge ahbl_reset_n )

// ahbl_to_lmmi_bridge
endmodule



`timescale 1ns/100ps
// =============================================================================
//                           COPYRIGHT NOTICE
// Copyright 2024 (c) Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// This confidential and proprietary software may be used only as authorized by
// a licensing agreement from Lattice Semiconductor Corporation.
// The entire notice above must be reproduced on all authorized copies and
// copies may only be made to the extent permitted by a licensing agreement from
// Lattice Semiconductor Corporation.
//
// Lattice Semiconductor Corporation        TEL : 1-800-Lattice (USA and Canada)
// 5555 NE Moore Court                            408-826-6000 (other locations)
// Hillsboro, OR 97124                     web  : http://www.latticesemi.com/
// U.S.A                                   email: techsupport@lscc.com
// =============================================================================
//-F I L E D E T A I L S-------------------------------------------------------
// Description  : This module is used to transfer pulse from one clock domain to
//                to other clock domain.
//-----------------------------------------------------------------------------
module ahbl_to_lmmi_inst_ipgen_pulse_sync (
    input inclk, 
    input outclk, 
    input inclk_reset_n, 
    input outclk_reset_n, 
    input indata_i, 
    output outdata_o) ;
    // Unit delay parameter for Simulation purpose.
    parameter UD = 1 ; 
    reg indata_f ; 
    reg outdata_f1 ; 
    reg outdata_f2 ; 
    reg outdata_f3 ; 
    //------..-----..-----..-----..-----..-----..-----..-----..-----..-----..-----
    //                Read this before you begin,
    // This method is used only to synchronize pulse of 1 clock duration when it passes
    // clock domain.
    // In other words, indata_i must ( must again ) be a pulse of 1 clock ( inclk )duration.
    // It's better if indata_i is an output of a flip-flop.
    //------..-----..-----..-----..-----..-----..-----..-----..-----..-----..-----
    //  Input T flip Flop design
    always
        @(posedge inclk or 
            negedge inclk_reset_n)
        if ((~inclk_reset_n)) 
            indata_f <= #(UD)   1'b0 ;
        else
            if (indata_i) 
                // for active low input pulse comment this line and remove comment from below line
                //if(~indata_i)
                indata_f <= #(UD)   (~indata_f) ;
    // Flop indata_i using outclk
    always
        @(posedge outclk or 
            negedge outclk_reset_n)
        if ((~outclk_reset_n)) 
            outdata_f1 <= #(UD)   1'b0 ;
        else
            outdata_f1 <= #(UD)   indata_f ;
    // Flop indata_i using outclk
    always
        @(posedge outclk or 
            negedge outclk_reset_n)
        if ((~outclk_reset_n)) 
            outdata_f2 <= #(UD)   1'b0 ;
        else
            outdata_f2 <= #(UD)   outdata_f1 ;
    // Flop indata_i using outclk
    always
        @(posedge outclk or 
            negedge outclk_reset_n)
        if ((~outclk_reset_n)) 
            outdata_f3 <= #(UD)   1'b0 ;
        else
            outdata_f3 <= #(UD)   outdata_f2 ;
    assign outdata_o = (outdata_f2 ^ outdata_f3) ; // for active low input pulse comment this line and remove comment from below line

//assign outdata_o = ~(outdata_f2 ^ outdata_f3);
endmodule



`timescale 1ns/100ps
// =============================================================================
//                           COPYRIGHT NOTICE
// Copyright 2024 (c) Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// This confidential and proprietary software may be used only as authorized by
// a licensing agreement from Lattice Semiconductor Corporation.
// The entire notice above must be reproduced on all authorized copies and
// copies may only be made to the extent permitted by a licensing agreement from
// Lattice Semiconductor Corporation.
//
// Lattice Semiconductor Corporation        TEL : 1-800-Lattice (USA and Canada)
// 5555 NE Moore Court                            408-826-6000 (other locations)
// Hillsboro, OR 97124                     web  : http://www.latticesemi.com/
// U.S.A                                   email: techsupport@lscc.com
// =============================================================================
//-F I L E D E T A I L S-------------------------------------------------------
// Description  : This module is used for synchronizing the multi bit data with
//                the use of synchronized pulse and acknowledged pulse is
//                returned. This technique is known as Multi Cycle Path (MCP)
//                Formulation with acknowledged feedback.
//-----------------------------------------------------------------------------
module ahbl_to_lmmi_inst_ipgen_sync_mcp_ack_fdbk (
    input inclk,  // clock signal of sending clock domain
    input inclk_reset_n,  // reset signal synchronized with "inclk"
    input indata_send_pl_i,  // send pulse
    output inclk_ack_pl_o,  // ready signal ( ACK is received from "outclk" domain )
    input outclk,  // clock signal of receiving clock domain
    input outclk_reset_n,  // reset signal synchronized with "outclk"
    input outclk_data_ld_i,  // load signal synchronized with "outclk"
    output outdata_ld_pl_o // load pulse synchronized with "outclk"
        ) ;
    //===================================================
    //
    // Parameter Declaration
    //
    //===================================================
    // Unit delay parameter for Simulation purpose.
    parameter UD = 1'b1 ; 
    //=====================================================================================
    //
    // Instance of "pulse_sync" module.
    //
    // This module will synchronize the "indata_send_pl_i" pulse with "out_clk" which is
    // read request from the avalon master side.
    //
    //======================================================================================
    ahbl_to_lmmi_inst_ipgen_pulse_sync ubps1 (.inclk(inclk), 
                .outclk(outclk), 
                .inclk_reset_n(inclk_reset_n), 
                .outclk_reset_n(outclk_reset_n), 
                .indata_i(indata_send_pl_i), 
                .outdata_o(outdata_ld_pl_o)) ; 
    //==========================================================================================
    //
    //    Instance of "pulse_sync" module.
    //
    // -> The purpose of this instance is to provide the "u_read_data_valid" pulse to "inclk"
    //    domain with "read data".
    //
    // -> So this pulse synchronizer will take this pulse and generate "inclk_ack_pl_o"
    //    pulse synchronized with "inclk" domain.
    //
    // -> "inclk_ack_pl_o" will be used to de assert wait request signal.
    //
    //===========================================================================================
    ahbl_to_lmmi_inst_ipgen_pulse_sync ubps2 (.inclk(outclk), 
                .outclk(inclk), 
                .inclk_reset_n(outclk_reset_n), 
                .outclk_reset_n(inclk_reset_n), 
                .indata_i(outclk_data_ld_i), 
                .outdata_o(inclk_ack_pl_o)) ; 
endmodule


