/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.9.1
    2026 03 18 10:29:28
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll_multiclk (clki_i, clkop_o, clkos_o, clkos2_o, lock_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
    output  lock_o;
endmodule