// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// --------------------------------------------------------------------------
// Copyright (c) 2019-2024 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// --------------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT,SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE.
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// --------------------------------------------------------------------------

/****************************************************************************/
/**
 *
 * @file lsc_uvc.c
 * @addtogroup lscusb Overview
 * @{
 *
 *
 *****************************************************************************/


#include <stdio.h>
#include "lsc_usb_dev.h"
#include "lsc_usb_ch9.h"
#include "lsc_uvc.h"
#include "../lsc_in_ep_buf_mgmt.h"
#include "i2c_master.h"
#include "i2c_master_regs.h"
#include "uvc/camera_initialization.h"
#include "../utils.h"

extern struct i2cm_instance i2c_master_core;
extern uint16_t cam_chip_id;  // Camera chip ID from main.c

uint8_t data[64]__attribute__((aligned(4))) , terminalErrorCode[2], var __attribute__((aligned(4))) = 0/*, straming_en = 0*/;
volatile uint8_t straming_en, i2c_stat = 0;
volatile uint32_t bmCtrlsSupported[NO_OF_TERMINALS];
uint32_t temp, selectProcUnitCtrlsArrayCol = 0, selectProcUnitCtrlsArrayRow = 0, selectExtenUnitCtrlsArrayCol = 0, selectExtenUnitCtrlsArrayRow = 0;
volatile uint16_t procUnitCtrlsVal[NO_PROC_UNIT_CONTROLS_SUPPORTED][6], ExtenUnitCtrlsVal[NO_OF_EXTENSION_UNIT_CONTROLS_SUPPORTED][6];

VIDEO_PROBE_AND_COMMIT_CONTROL vdoProbeCommit, TempVdoProbeCommit;
VIDEO_STILL_IMG_PROBECOMMIT_CONTROL vdoStillImgProbeComit, TempStillImgVdoProbeCommit;
FORMAT_OF_PAYLOAD_HEADER vdoFormatPayloadHeader;

volatile uint8_t resolution_change_pending = 0;
volatile camera_resolution_t current_resolution = RESOLUTION_1280x720;

//uint8_t i2c_rx_bufr[256] __attribute__((aligned(4))) = { 0 };
uint16_t i2c_tx_len = 0;

uint8_t i2c_tx_bufr[64] __attribute__((aligned(8)))/*__attribute__((section(".myBufSection")))*/ = { 0 };
//extern uint8_t res_buf[256] __attribute__ ((aligned(8)))__attribute__((section(".myBufSection")));
uint16_t i2c_rx_len = 0;

/****************************************************************************/
/**
 * @brief UVC Class-Specific Request Handler
 * 
 * This function handles all UVC (USB Video Class) class-specific requests
 * from the host (e.g., PotPlayer). It is the main entry point for resolution
 * change requests.
 * 
 * Resolution Change Flow:
 * 
 * Phase 1: Host sends VS_PROBE_CONTROL (SET) request
 *   - PotPlayer probes if device supports the requested resolution
 *   - Driver extracts frame index and calculates frame sizes
 * 
 * Phase 2: Host sends VS_COMMIT_CONTROL (SET) request
 *   - PotPlayer commits to the new format
 *   - Driver performs resolution change:
 *     * If streaming active: Defers hardware change (sets flag)
 *     * If streaming inactive: Performs immediate hardware change
 * 
 * Phase 3: Deferred Change (if needed)
 *   - Main loop detects resolution_change_pending flag
 *   - Performs hardware register changes when safe
 * 
 * @param dev Pointer to USB device structure
 * @param setup_pkt Pointer to USB setup packet containing the request
 * 
 * @note This function routes to specific handlers based on:
 *       - Interface number (Video Control vs Video Streaming)
 *       - Control selector (Probe, Commit, etc.)
 *       - Request direction (GET vs SET)
 * 
 ****************************************************************************/
void lsc_usb_class_req(struct lsc_usb_dev *dev, setup_pkt *setup_pkt)
{
    struct lsc_usb_dev *usb_dev;
    usb_dev = (struct lsc_usb_dev*)dev;
    uint32_t resp_len = 0, data_size = 0, err = 0;

    printf("Setup Pkt: %x %x %2x %2x %2x\r\n", setup_pkt->bRequestType,
            setup_pkt->bRequest, setup_pkt->wValue, setup_pkt->wIndex,
            setup_pkt->wLength);

    /*
     * Direction -- USB_EP_DIR_IN or USB_EP_DIR_OUT
     */
    uint8_t dir = !!(setup_pkt->bRequestType & LSC_USB_DIR_IN);

    if ((setup_pkt->bRequestType & USB_RECIPIENT_MASK) == USB_RECIPIENT_INTERFACE)
    {
        if(((setup_pkt->wIndex & 0xFF) == 0) && (((setup_pkt->wIndex >> 8) & 0xFF) == 0))
        {
            /***
            * This means that request came for video control interface
            * not to some unit/terminal in video control interface
            ***/

            printf("VC_0_0\r\n");

            temp = (setup_pkt->wValue>> 8) & 0xFF;

            switch (setup_pkt->bRequest)
            {
                case GET_CUR:

                    switch (temp)
                    {
                        case VC_REQUEST_ERROR_CODE_CONTROL:

                            var = terminalErrorCode[VC_ERR_CODE_INDEX];
                            data_size = 1;
                            err = 0;

                            break;

                        case VC_VIDEO_POWER_MODE_CONTROL:

                            err = 1;

                            break;
                    }

                    break;

                case GET_INFO:

                    switch (temp)
                    {
                        case VC_REQUEST_ERROR_CODE_CONTROL:
                            var = 0x01; //(unsigned char*)terminalErrorCode[VC_ERR_CODE_INDEX];
                            data_size = 1;

                            break;

                        case VC_VIDEO_POWER_MODE_CONTROL:

                            err = 1;

                            break;
                    }

                    break;

                default:

                    var = ERR_CODE_NO_ERR;
                    data_size = 1;

                    err = 1;

                    break;
            }
            if (!err)
            {
                lsc_usb_ep0_send(usb_dev, (uint8_t*)&var, data_size);
            } else

            {
                terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_CTRL;

                lsc_usb_ep0_stall_restart(usb_dev);

                return;
            }
        }
        else if (((setup_pkt->wIndex & 0xFF) == 0) && (((setup_pkt->wIndex >> 8) & 0xFF) != 0))
        {
            /***
             * This means that request came for Unit/Terminal in video control interface
             ***/

            printf("VC_0_1\r\n");

            if (((setup_pkt->wIndex >> 8) & 0xFF) == RECEPIENT_IS_PROCESSING_UNIT)
            {
                printf("Processing Unit Req\r\n");

                selectProcUnitCtrlsArrayRow = ((setup_pkt->wValue >> 8) & 0xFF);

                if (!(bmCtrlsSupported[PU_BMCONTROLS_INDEX] & selectProcUnitCtrlsArrayRow))
                {
                    //if control not supported and request came for that Control Selector
                    //then HALT the control endpoint and sets the error code

                    printf(" PU Control not supported\r\n");

//                    printf(" PU Control not supported\r\n");

                    terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_CTRL;

                    lsc_usb_ep0_stall_restart(usb_dev);

                    return;
                }

                data_size = 0x02;

                switch (setup_pkt->bRequest)
                {
                    case GET_CUR:
                        selectProcUnitCtrlsArrayCol = GET_CUR_VAL_INDEX;
                        break;
                    case GET_DEF:
                        selectProcUnitCtrlsArrayCol = GET_DEF_VAL_INDEX;
                        break;
                    case GET_INFO:
                        data_size = 0x01;
                        selectProcUnitCtrlsArrayCol = GET_INFO_VAL_INDEX;
                        break;
                    case GET_LEN:
                        selectProcUnitCtrlsArrayCol = -1;
                        break;
                    case GET_MAX:
                        selectProcUnitCtrlsArrayCol = GET_MAX_VAL_INDEX;
                        break;
                    case GET_MIN:
                        selectProcUnitCtrlsArrayCol = GET_MIN_VAL_INDEX;
                        break;
                    case GET_RES:
                        selectProcUnitCtrlsArrayCol = GET_RES_VAL_INDEX;
                        break;

                    default:
                        printf(" Set PU\r\n");

                        terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_REQ;

                        lsc_usb_ep0_stall_restart(usb_dev);

                        return;
                }

                temp = (setup_pkt->wValue >> 8) & 0xFF;

                var = procUnitCtrlsVal[selectProcUnitCtrlsArrayRow][selectProcUnitCtrlsArrayCol];

                lsc_usb_ep0_send(usb_dev, (uint8_t*)&var, data_size);

            }
            else if (((setup_pkt->wIndex >> 8) & 0xFF) == RECEPIENT_IS_EXTENSION_UNIT)
            {
                printf(" Extension Unit req\r\n");

                selectExtenUnitCtrlsArrayRow = (setup_pkt->wValue >> 8) & 0xFF;;

                if (!(bmCtrlsSupported[EU_BMCONTROLS_INDEX] & selectExtenUnitCtrlsArrayRow))
                {
                    //if control not supported and request came for that Control Selector
                    //then HALT the control endpoint and sets the error code

                    printf("XU Control not supported\r\n");

                    terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_CTRL;

                    lsc_usb_ep0_stall_restart(usb_dev);

                    return;
                }

                if(!dir)
                {
                    //Means Host will Send Data
                    switch (usb_dev->ep0_state)
                    {
                        case LSC_EP0_SETUP_PHASE:
    //                        printf("setup\r\n");

                            if (setup_pkt->bRequest == SET_CUR)
                            {
                                printf(" Set EU\r\n");

                                lsc_usb_ep0_rcv(usb_dev, /*i2c_tx_bufr*/res_buf, setup_pkt->wLength);
                            }

                            break;

                        case LSC_EP0_DATA_PHASE:
    //                        printf("data\r\n");

                            i2c_tx_len = setup_pkt->wLength;

                          printf("i2c_tx_len:%x\r\n",i2c_tx_len);
//                          printf("Count:%x\r\n",i2c_tx_bufr[0]);

                          memcpy(i2c_tx_bufr, res_buf,i2c_tx_len);

//                           for(uint32_t k = 0; k<20; k++)
//                                printf("data: %x \r\n", i2c_tx_bufr[k]);

                            //If request is for I2C write only
                            if(i2c_tx_bufr[1] == 0)
                            {
//                                pI2cDev->slv_addr = 0x36;
    //                          i2c_rx_len = 0x3;//To read chip chip of camera sensor
    //                          rcvd_set_xu_data=1;
                                for(uint32_t i=0; i<i2c_tx_bufr[0]; i++)
                                {
                                    printf("Add:%x\r\n", ((i2c_tx_bufr[(i * 4) + 8] << 8)| (i2c_tx_bufr[(i * 4) + 9] /*<< 8*/)));
                                    printf("Val:%x\r\n", (i2c_tx_bufr[(i * 4) + 10] | (i2c_tx_bufr[(i * 4) + 11] << 8)));

//                                    pI2cDev->i2c_op_ongoing = 1;

                                    i2c_stat = i2c_master_write (&i2c_master_core,
                                                      TRGT_SLV_ADDR,
                                                      0x3,  // Every time fix 2 byte of offset address
                                                      &i2c_tx_bufr[(i * 4) + 8] // Tx length
                                                      );
                                    if(!i2c_stat)
                                        printf("I2C Wr success\r\n");
                                    else
                                        printf("I2C Wr fail\r\n");


//                                    if (pI2cDev->i2c_xfer_sts
//                                            == SUCCESS) {
//                                        printf( "I2C Wr Operation was successful.\r\n");
//                                    } else {
//                                        printf(
//                                                "I2C Wr Operation failed. I2C Transfer Status: 0x%x\r\n",
//                                                pI2cDev->i2c_xfer_sts);
//                                         USB30_SetStallEP((void*)usb30dev, 0x80);
//                                    }
                                }
    //                            no_of_bytes_successfully_written =
    //                                    i2c_tx_len
    //                                            - pI2cDev->not_transmitted_bytes;
    //                            no_of_bytes_successfully_read =
    //                                    i2c_rx_len
    //                                            - pI2cDev->not_received_bytes;
    //                            printf("No of bytes successfully written = 0x%x \r\n",
    //                                    no_of_bytes_successfully_written);
    //                            printf("No of bytes successfully read = 0x%x \r\n",
    //                                    no_of_bytes_successfully_read);
                            }

                            break;

                        default:
                            break;
                    }
                }
                else
                {
                    //Means Device will send Data

                    data_size = 0x02;

                    switch (setup_pkt->bRequest)
                    {
                        case GET_CUR:
                            selectExtenUnitCtrlsArrayCol = GET_CUR_VAL_INDEX;
                            {
                                printf("XU:GET_CUR\r\n");

//                                pI2cDev->slv_addr = 0x36;

                                for(uint32_t i=0; i<i2c_tx_bufr[0]; i++)
                                {
                                    printf("Add:%x\r\n", ((i2c_tx_bufr[(i * 4) + 8] << 8) | (i2c_tx_bufr[(i * 4) + 9] /*<< 8*/)));

//                                    pI2cDev->i2c_op_ongoing = 1;

                                    i2c_stat = i2c_master_repeated_start (
                                            &i2c_master_core,
                                            TRGT_SLV_ADDR,
                                            0x2,
                                            &i2c_tx_bufr[(i * 4) + 8],
                                            0x01,
                                            &i2c_tx_bufr[(i * 4) + 10]);

                                    if(!i2c_stat)
                                        printf("I2C Rd success\r\n");
                                    else
                                        printf("I2C Rd fail\r\n");

//                                    if (pI2cDev->i2c_xfer_sts
//                                            == SUCCESS) {
                                        printf( "I2C Rd Operation was successful.: %x\r\n", i2c_tx_bufr[(i * 4) + 10]/*, i2c_tx_bufr[(i * 4) + 11], i2c_tx_bufr[(i * 4) + 12]*/);

//
//    //                                    PCtrlEpReqStatus->PDataStageData = &i2c_rx_bufr[(i * 2)];
//    //                                     //printf("CS: %x\r\n", *PCtrlEpReqStatus->PDataStageData);
//    //                                     PCtrlEpReqStatus->sizeOfDataStageData = (2 * i2c_tx_bufr[0]);
//
//                                    } else {
//                                        printf(
//                                                "I2C Rd Operation failed. I2C Transfer Status: 0x%x\r\n",
//                                                pI2cDev->i2c_xfer_sts);
//                                         USB30_SetStallEP((void*)usb30dev, 0x80);
//                                    }
                                }
//                                PCtrlEpReqStatus->PDataStageData = &i2c_tx_bufr[0];

    //                            for(uint32_t i=0; i<((4 * i2c_tx_bufr[0]) + 8); i++)
    //                                printf("%x  ", *(PCtrlEpReqStatus->PDataStageData +i));
    //
    //                            printf("\r\n");
                                 //printf("CS: %x\r\n", *PCtrlEpReqStatus->PDataStageData);

//                                PCtrlEpReqStatus->sizeOfDataStageData = (4 * i2c_tx_bufr[0]) + 8;

                                lsc_usb_ep0_send(usb_dev, &i2c_tx_bufr[0], ((4 * i2c_tx_bufr[0]) + 8));
                            }
                            break;
                        case GET_DEF:
                            selectExtenUnitCtrlsArrayCol = GET_DEF_VAL_INDEX;
                            lsc_usb_ep0_send(usb_dev, &var, data_size);

                            break;
                        case GET_INFO:
                            data_size = 0x01;
                            var = 0x3;
//                            selectExtenUnitCtrlsArrayCol = GET_INFO_VAL_INDEX;
                            lsc_usb_ep0_send(usb_dev, &var, data_size);

                            break;
                        case GET_LEN:
                            printf("Get XU Len\r\n");
                            var = 0x58;
//                            printf("var: %x\r\n", var);
//                            selectExtenUnitCtrlsArrayCol = -1;
                            lsc_usb_ep0_send(usb_dev, &var, data_size);

                            break;
                        case GET_MAX:
                            selectExtenUnitCtrlsArrayCol = GET_MAX_VAL_INDEX;
                            lsc_usb_ep0_send(usb_dev, &var, data_size);
                            break;
                        case GET_MIN:
                            selectExtenUnitCtrlsArrayCol = GET_MIN_VAL_INDEX;
                            lsc_usb_ep0_send(usb_dev, &var, data_size);
                            break;
                        case GET_RES:
                            selectExtenUnitCtrlsArrayCol = GET_RES_VAL_INDEX;
                            lsc_usb_ep0_send(usb_dev, &var, data_size);
                            break;

                        default:

                            printf(" Set default EU\r\n");

                            terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_REQ;

                            lsc_usb_ep0_stall_restart(usb_dev);

                            break;
                    }

//                    temp = (setup_pkt->wValue >> 8) & 0xFF;
//
//                    var = ExtenUnitCtrlsVal[selectExtenUnitCtrlsArrayRow][selectExtenUnitCtrlsArrayCol];
//
//                    lsc_usb_ep0_send(usb_dev, (uint8_t*)&var, data_size);
                }

            } else if (((setup_pkt->wIndex >> 8) & 0xFF) == RECEPIENT_IS_OUTPUT_TERMINAL)
            {
                printf(" O/P_Term req\r\n");

                terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_REQ;

                lsc_usb_ep0_stall_restart(usb_dev);

                return;

            } else if (((setup_pkt->wIndex >> 8) & 0xFF) == RECEPIENT_IS_CAMERA_TERMINAL)
            {
                printf("\n Camera_Term Req");

                terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_CTRL;

                lsc_usb_ep0_stall_restart(usb_dev);

                return;

            } else
            {
                printf("\n Vc Recepient !supported Req");

                lsc_usb_ep0_stall_restart(usb_dev);

                terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_UNIT;

                return;

            }
        }
        else if (((setup_pkt->wIndex & 0xFF) == 1) && (((setup_pkt->wIndex >> 8) & 0xFF) == 0))
        {
            /***
             * This means that request came for video streaming interface 1 alternate setting 0
             **/

            printf("VS_1_0\r\n");

            if(dir == 1) // Device to Host
            {
//                printf("Get Req\r\n");

                switch ((setup_pkt->wValue >> 8) & 0xFF)
                {
                    case VS_PROBE_CONTROL:

                        printf("Get - PRB_CTRL\r\n");

                        resp_len = setup_pkt->wLength > sizeof(VIDEO_PROBE_AND_COMMIT_CONTROL) ? sizeof(VIDEO_PROBE_AND_COMMIT_CONTROL) : setup_pkt->wLength;

                        lsc_usb_ep0_send(usb_dev, (uint8_t*)&vdoProbeCommit, sizeof(VIDEO_PROBE_AND_COMMIT_CONTROL));

                        break;

                    case VS_STILL_PROBE_CONTROL:

                        printf("Still Probe\r\n");

                        resp_len = setup_pkt->wLength > sizeof(VIDEO_STILL_IMG_PROBECOMMIT_CONTROL) ? sizeof(VIDEO_STILL_IMG_PROBECOMMIT_CONTROL) : setup_pkt->wLength;

                        lsc_usb_ep0_send(usb_dev, (uint8_t*)&vdoStillImgProbeComit, sizeof(VIDEO_STILL_IMG_PROBECOMMIT_CONTROL));

                        break;

                    case VS_COMMIT_CONTROL:

                        printf("Get: Commit Control\r\n");

                        lsc_usb_ep0_send(usb_dev, (uint8_t*)&vdoStillImgProbeComit, setup_pkt->wLength);

                        break;

                    case VS_STILL_COMMIT_CONTROL:

                        printf("Still Commit Control\r\n");

                        break;

                    default:

                        printf("Unsupported Control Selector\r\n");

                        terminalErrorCode[VC_ERR_CODE_INDEX] = -1; ///ERR_CODE_INVALID_CTRL;

                        lsc_usb_ep0_stall_restart(usb_dev);

                        return;
                }
            }
            else if(dir == 0x0) // Host to Device
            {
//                printf("Set Req\r\n");

                switch (usb_dev->ep0_state)
                {
                    case LSC_EP0_SETUP_PHASE:
//                        printf("setup\r\n");
                        lsc_usb_ep0_rcv(usb_dev, /*data*/res_buf, setup_pkt->wLength);

                        break;

                    case LSC_EP0_DATA_PHASE:
//                        printf("data\r\n");
                        switch ((setup_pkt->wValue >> 8) & 0xFF)
                        {
                            case VS_PROBE_CONTROL:
                                /**
                                 * Phase 2: Probe Control Request (SET) - Host to Device
                                 * 
                                 * This is the first step in the UVC resolution change sequence.
                                 * PotPlayer sends a VS_PROBE_CONTROL request with the desired
                                 * frame format (resolution) to probe if the device supports it.
                                 * 
                                 * Flow:
                                 * 1. Host sends probe control data via EP0
                                 * 2. Driver receives data in res_buf[]
                                 * 3. Extract bFrameIndex to determine requested resolution
                                 * 4. Calculate frame sizes (deferred if streaming is active)
                                 * 5. Return probe control structure to host
                                 */

                                printf("Set - PRB_CTRL\r\n");

                                memcpy(&vdoProbeCommit, /*data*/res_buf, setup_pkt->wLength);

//                                for(uint32_t i = 0; i < setup_pkt->wLength; i++)
//                                  printf("%x ", data[i]);
//
//                                printf("\r\n");
                                // Extract requested resolution from frame index
                                // Frame index maps to resolution:
                                //   FRAME_INDEX_1920x1080 (0x01) → RESOLUTION_1920x1080
                                //   FRAME_INDEX_1280x720  (0x02) → RESOLUTION_1280x720
                                uint8_t requested_frame_index = vdoProbeCommit.bFrameIndex;
                                uint16_t req_width, req_height;
                                camera_resolution_t requested_resolution;
                                
                                if (requested_frame_index == FRAME_INDEX_1920x1080) {
                                    req_width = 1920;
                                    req_height = 1080;
                                    requested_resolution = RESOLUTION_1920x1080;
                                } else if (requested_frame_index == FRAME_INDEX_1280x720) {
                                    req_width = 1280;
                                    req_height = 720;
                                    requested_resolution = RESOLUTION_1280x720;
                                } else {
                                    // Invalid frame index - reject the probe request
                                    printf("VS_PROBE_CONTROL: INVALID frame_index=0x%02x, rejecting\r\n", requested_frame_index);
                                    terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_VALUE_WITHIN_RANGE;
                                    lsc_usb_ep0_stall_restart(usb_dev);
                                    return;
                                }
                                
                                // Frame size calculation strategy:
                                // - ALWAYS update frame sizes in probe response to match requested resolution
                                //   (Probe response must be correct for PotPlayer to accept it)
                                // - If streaming IS active AND resolution changes: Hardware change is deferred to main.c
                                //   (But probe response frame sizes are updated immediately)
                                uint8_t hardware_change_deferred = (straming_en && (requested_resolution != current_resolution));
                                
                                // Always update bFrameIndex and frame sizes in probe response based on REQUESTED resolution
                                // This ensures PotPlayer receives correct values even if hardware change is deferred
                                // Ensure bFrameIndex matches the requested resolution
                                vdoProbeCommit.bFrameIndex = requested_frame_index;
#if UVC_ISO
                                vdoProbeCommit.dwMaxPayloadTransferSize = (ISO_TRANSFER_SZ); // ((WIDTH*HEIGHT*BITSPERPIXEL)/8) + 2;                //0x96002;
#ifdef UVC_YUY2
                                vdoProbeCommit.dwMaxVideoFrameSize = ((req_width*req_height*BITSPERPIXEL)/8) + 2;
#else
                                ////0x003F4800 static value was there in MJPEG HAL as in that with this equation not getting expected results.
                                vdoProbeCommit.dwMaxVideoFrameSize = 0x003F4800;
#endif
#else
                                vdoProbeCommit.dwMaxPayloadTransferSize = ((req_width
                                        * req_height * BITSPERPIXEL) / 8) + 2;
#ifdef UVC_YUY2
                                vdoProbeCommit.dwMaxVideoFrameSize = ((req_width
                                        * req_height * BITSPERPIXEL) / 8) + 2;
#else
                                ////0x003F4800 static value was there in MJPEG HAL as in that with this equation not getting expected results.
                                vdoProbeCommit.dwMaxVideoFrameSize = 0x003F4800;
#endif
#endif

                                break;

                            case VS_STILL_PROBE_CONTROL:

                                printf("Still Probe Control\r\n");

                                // memcpy(&TempVdoProbeCommit, data, setup_pkt->wLength);
                                memcpy(&TempVdoProbeCommit, res_buf, setup_pkt->wLength);

                                break;

                            case VS_COMMIT_CONTROL:
                            {
                                /**
                                 * Phase 3: Commit Control Request (SET) - Host to Device
                                 * 
                                 * This is the second step in the UVC resolution change sequence.
                                 * After probing, PotPlayer sends VS_COMMIT_CONTROL to commit the new format.
                                 * This is where the actual resolution change logic is executed.
                                 * 
                                 * Flow:
                                 * 1. USB Power Management: Disable U1/U2 sleep states during streaming
                                 * 2. Resolution Detection: Extract and validate requested resolution
                                 * 3. Resolution Change Logic:
                                 *    - If streaming active: Defer hardware change (set flag)
                                 *    - If streaming inactive: Perform immediate hardware change
                                 * 4. Update probe/commit structure with new values
                                 * 5. Initialize streaming buffers and enable streaming
                                 */

                                printf("Commit Probe Control\r\n");
                                
                                // USB Power Management: Disable U1/U2 sleep states during streaming
                                // This prevents the USB controller from entering low-power modes
                                // which could interrupt video streaming
								lsc_set_u1_sleep(usb_dev, U1U2_DIS);
								lsc_set_u2_sleep(usb_dev, U1U2_DIS);
								lsc_usb_accept_u1u2_sleep(usb_dev, U1U2_DIS);

                                // Copy commit control data from host
                                memcpy(&TempVdoProbeCommit, res_buf, setup_pkt->wLength);
                                
                                // Resolution Detection: Extract and validate requested resolution from frame index
                                uint8_t requested_frame_index = TempVdoProbeCommit.bFrameIndex;
                                camera_resolution_t requested_resolution;
                                
                                if (requested_frame_index == FRAME_INDEX_1920x1080) {
                                    requested_resolution = RESOLUTION_1920x1080;
                                } else if (requested_frame_index == FRAME_INDEX_1280x720) {
                                    requested_resolution = RESOLUTION_1280x720;
                                } else {
                                    // Invalid frame index - reject the commit request
                                    printf("VS_COMMIT_CONTROL: INVALID frame_index=0x%02x, rejecting\r\n", requested_frame_index);
                                    terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_VALUE_WITHIN_RANGE;
                                    lsc_usb_ep0_stall_restart(usb_dev);
                                    return;
                                }
                                
                                // Resolution Change Logic: Two scenarios based on streaming status
                                if (requested_resolution != current_resolution) {
                                    if (straming_en) {
                                        /**
                                         * Scenario A: Streaming Active (straming_en == 1)
                                         * 
                                         * Hardware change is deferred to avoid interrupting active video stream.
                                         * The resolution change will be performed in the main() loop when
                                         * streaming stops or during the next iteration.
                                         * 
                                         * Steps:
                                         * 1. Set resolution_change_pending flag
                                         * 2. Update current_resolution variable (for main.c to use)
                                         * 3. Skip hardware register changes (deferred)
                                         * 4. Skip frame size updates (deferred to main.c)
                                         */
                                        resolution_change_pending = 1;
                                        // Update current_resolution now so main.c can use it when performing the hardware change
                                        current_resolution = requested_resolution;
                                    } else {
                                        /**
                                         * Scenario B: Streaming NOT Active (straming_en == 0)
                                         * 
                                         * Perform synchronous resolution change immediately.
                                         * This is safe because no video stream is active.
                                         * 
                                         * Steps:
                                         * 1. Disable camera (I2C register writes)
                                         * 2. Wait 10ms for camera to fully disable
                                         * 3. Re-initialize common registers (skip PLL registers)
                                         * 4. Update current_resolution variable
                                         * 5. Set resolution-specific registers via I2C
                                         * 6. Configure PLL based on USB speed (USB 2.0 or 3.0)
                                         * 7. Wait 20ms for PLL/resolution stabilization
                                         * 8. Re-enable camera with new resolution
                                         * 9. Clear resolution_change_pending flag
                                         */
                                        if (cam_chip_id == IMX219_SENSOR_ID) {
                                            // Disable camera before resolution change
                                            disable_camera();
                                            
                                            // Add delay to ensure camera is fully disabled
                                            delayMS(10);
                                            
                                            // Re-initialize ALL common registers (including PLL registers)
                                            // This matches the enumeration initialization sequence exactly
                                            // PLL registers will be overwritten in the next step
                                            mode_default_register_init();
                                            
                                            // Update current_resolution before setting new resolution
                                            current_resolution = requested_resolution;
                                            
                                            // Update PLL settings based on resolution and USB speed
                                            // PLL must be set after common registers but before resolution-specific registers
                                            // This matches the enumeration sequence: common init → PLL → resolution
                                            if (usb_dev->dev_speed == LSC_SPEED_SUPER) {
                                                usb3_cam_pll_setting(current_resolution);
                                            } else {
                                                usb2_cam_pll_setting(current_resolution);
                                            }
                                            
                                            // Update resolution-specific registers
                                            set_resolution(current_resolution);
                                            
                                            // Add stabilization delay after PLL and resolution changes
                                            delayMS(20);
                                            
                                            // Re-enable camera with new resolution
                                            enable_camera();
                                            
                                            // Clear resolution_change_pending since we handled it synchronously
                                            resolution_change_pending = 0;
                                        } else {
                                            // For non-IMX219, just update the resolution variable
                                            current_resolution = requested_resolution;
                                        }
                                    }
                                } else {
                                    // No resolution change needed, but update current_resolution to be safe
                                    current_resolution = requested_resolution;
                                }
                                
                                // Probe/Commit Structure Update: Copy all values from host
                                vdoProbeCommit.bmHint.val =
                                        TempVdoProbeCommit.bmHint.val;
                                vdoProbeCommit.bFormatIndex =
                                        TempVdoProbeCommit.bFormatIndex;
                                
                                // Ensure bFrameIndex matches the actual current_resolution
                                // (This may differ from host request if change was deferred)
                                if (current_resolution == RESOLUTION_1920x1080) {
                                    vdoProbeCommit.bFrameIndex = FRAME_INDEX_1920x1080;
                                } else {
                                    vdoProbeCommit.bFrameIndex = FRAME_INDEX_1280x720;
                                }
                                
                                vdoProbeCommit.dwFrameInterval =
                                        TempVdoProbeCommit.dwFrameInterval;
                                vdoProbeCommit.wKeyFrameRate =
                                        TempVdoProbeCommit.wKeyFrameRate;
                                vdoProbeCommit.wPFrameRate =
                                        TempVdoProbeCommit.wPFrameRate;
                                vdoProbeCommit.wCompQuality =
                                        TempVdoProbeCommit.wCompQuality;
                                vdoProbeCommit.wCompWindowSize =
                                        TempVdoProbeCommit.wCompWindowSize;
                                vdoProbeCommit.wDelay =
                                        TempVdoProbeCommit.wDelay;
                                
                                // Frame Size Update: Calculate based on actual current_resolution
                                // Formula: (width * height * BITSPERPIXEL) / 8 + 2
                                // 
                                // Strategy:
                                // - If streaming active AND resolution change pending: Skip update
                                //   (Frame sizes will be updated in main.c after hardware change completes)
                                // - Otherwise: Update frame sizes immediately
                                if (!(straming_en && resolution_change_pending)) {
                                    if (current_resolution == RESOLUTION_1920x1080) {
                                        vdoProbeCommit.dwMaxVideoFrameSize = ((1920 * 1080 * BITSPERPIXEL) / 8) + 2;
                                        vdoProbeCommit.dwMaxPayloadTransferSize = ((1920 * 1080 * BITSPERPIXEL) / 8) + 2;
                                    } else {
                                        vdoProbeCommit.dwMaxVideoFrameSize = ((1280 * 720 * BITSPERPIXEL) / 8) + 2;
                                        vdoProbeCommit.dwMaxPayloadTransferSize = ((1280 * 720 * BITSPERPIXEL) / 8) + 2;
                                    }
                                }
#ifdef UVC1_5
                                //UVC1.1
                                vdoProbeCommit.dwClockFrequency =
                                        TempVdoProbeCommit.dwClockFrequency;
                                vdoProbeCommit.bmFramingInfo =
                                        TempVdoProbeCommit.bmFramingInfo;
                                vdoProbeCommit.bPreferedVersion =
                                        TempVdoProbeCommit.bPreferedVersion;
                                vdoProbeCommit.bMinVersion =
                                        TempVdoProbeCommit.bMinVersion;
                                vdoProbeCommit.bMaxVersion =
                                        TempVdoProbeCommit.bMaxVersion;

                                //UVC1.5
                                vdoProbeCommit.bUsage =
                                        TempVdoProbeCommit.bUsage;
                                vdoProbeCommit.bBitDepthLuma =
                                        TempVdoProbeCommit.bBitDepthLuma;
                                vdoProbeCommit.bmSettings =
                                        TempVdoProbeCommit.bmSettings;
                                vdoProbeCommit.bMaxNumberOfRefFramesPlus1 =
                                        TempVdoProbeCommit.bMaxNumberOfRefFramesPlus1;
                                vdoProbeCommit.bmRateControlModes =
                                        TempVdoProbeCommit.bmRateControlModes;
                                vdoProbeCommit.bmLayoutPerStream[0] =
                                        TempVdoProbeCommit.bmLayoutPerStream[0];
#endif

                                // Streaming Initialization: Prepare buffers and enable streaming
                                lsc_iebm_buf_mgmt_init();
								lsc_32_write((LSC_IEBM_BUF_MGMT_IP_BASE + LSC_IEBM_CTRL_REG), LSC_IEBM_IP_CNF_MASK);
								straming_en = 1;  // Mark streaming as active
                                // Set configured bit in CTRL register

                                break;
                            }

                            case VS_STILL_COMMIT_CONTROL:

                                printf("Still Commit Control\r\n");

                                // memcpy(&TempVdoProbeCommit, data, setup_pkt->wLength);
                                memcpy(&TempVdoProbeCommit, res_buf, setup_pkt->wLength);

                                vdoStillImgProbeComit.bFormatIndex =
                                        TempStillImgVdoProbeCommit.bFormatIndex;
                                vdoStillImgProbeComit.bFrameIndex =
                                        TempStillImgVdoProbeCommit.bFrameIndex;
                                vdoStillImgProbeComit.bCompressionIndex =
                                        TempStillImgVdoProbeCommit.bCompressionIndex;
                                vdoStillImgProbeComit.dwMaxVideoFrameSize =
                                        TempStillImgVdoProbeCommit.dwMaxVideoFrameSize;
                                vdoStillImgProbeComit.dwMaxPayloadTransferSize =
                                        TempStillImgVdoProbeCommit.dwMaxPayloadTransferSize;

                                break;

                            case VS_STILL_IMAGE_TRIGGER_CONTROL:

                                printf("Still Image Trigger Control\r\n");

                                break;

                            default:

                                printf("Unsupported Control Selector\r\n");

                                terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_CTRL;

                                lsc_usb_ep0_stall_restart(usb_dev);

                                return;
                        }

                        break;

                    default:
                        break;
                }
            }
            else
            {
                printf("Unsupported Direction\r\n");

                lsc_usb_ep0_stall_restart(usb_dev);

                terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_WRONG_STATE;

                return;
            }
        }
        else
        {
            printf("Unsupported Interface\r\n");

            terminalErrorCode[VC_ERR_CODE_INDEX] = ERR_CODE_INVALID_UNIT;

            lsc_usb_ep0_stall_restart(usb_dev);

            return;
        }
    }
    else
    {
        printf("Recipient != Interface\r\n");
    }
}


void configure_uvc_device()
{
    unsigned data_size = 0;

    //Video Probe and Commit Control Data Structure

    vdoProbeCommit.bmHint.val = 0x0000;
    vdoProbeCommit.bFormatIndex = 0x01;
    if (current_resolution == RESOLUTION_1920x1080) {
        vdoProbeCommit.bFrameIndex = FRAME_INDEX_1920x1080;  // 0x01
    } else {
        vdoProbeCommit.bFrameIndex = FRAME_INDEX_1280x720;   // 0x02
    }
    
    vdoProbeCommit.dwFrameInterval = 0x51615; //0x00041FBE;//0x00036AD9;//0x0015CC5B;//0x004C4B40;//0x00145000;//0x989680;//0x51615;
    vdoProbeCommit.wKeyFrameRate = 0x00;               //(unsigned int)0x0960;
    vdoProbeCommit.wPFrameRate = 0x0000;
    vdoProbeCommit.wCompQuality = 0x0000;
    vdoProbeCommit.wCompWindowSize = 0x0000;
    vdoProbeCommit.wDelay = 0x0000;
#ifdef UVC_YUY2
    // Calculate frame sizes based on current resolution
    uint16_t current_width, current_height;
    if (current_resolution == RESOLUTION_1920x1080) {
        current_width = 1920;
        current_height = 1080;
    } else {
        current_width = 1280;
        current_height = 720;
    }
    vdoProbeCommit.dwMaxVideoFrameSize = ((current_width * current_height * BITSPERPIXEL) / 8)
            + 2;               //0x96002;//25500;//Commented in JPEG hal
    vdoProbeCommit.dwMaxPayloadTransferSize = ((current_width * current_height * BITSPERPIXEL)
            / 8) + 2;               //0x96002;//0x0000020C;//84  //Commented in JPEG hal
#else
    vdoProbeCommit.dwMaxVideoFrameSize = 0x003F4800;//JPEG change
    vdoProbeCommit.dwMaxPayloadTransferSize =0x3F4802;//JPEG change
#endif

#ifdef UVC1_5
    //UVC1.1
    vdoProbeCommit.dwClockFrequency=0x00;
    vdoProbeCommit.bmFramingInfo.val=0x00;
    vdoProbeCommit.bPreferedVersion=0x00;
    vdoProbeCommit.bMinVersion=0x00;
    vdoProbeCommit.bMaxVersion=0x00;

    //UVC1.5
    vdoProbeCommit.bUsage=0x00;
    vdoProbeCommit.bBitDepthLuma=0x00;
    vdoProbeCommit.bmSettings=0x00;
    vdoProbeCommit.bMaxNumberOfRefFramesPlus1=0x00;
    vdoProbeCommit.bmRateControlModes=0x00;
    vdoProbeCommit.bmLayoutPerStream[0]=0x00;
#endif

    //Video Still Image Probe and Commit Control Data Structure

    vdoStillImgProbeComit.bFormatIndex = 0x01;
    vdoStillImgProbeComit.bFrameIndex = 0x01;
    vdoStillImgProbeComit.bCompressionIndex = 0x00;                    //0x01;
    vdoStillImgProbeComit.dwMaxVideoFrameSize = 0x00FFFFFF;      //0x00070800;
    vdoStillImgProbeComit.dwMaxPayloadTransferSize = 0x000800; //0x0000020C;//0x0202;

    vdoFormatPayloadHeader.bmHeaderInfo.byte = 0x21;
    vdoFormatPayloadHeader.bHeaderLength = 2;

    bmCtrlsSupported[PU_BMCONTROLS_INDEX] = 0x00000000;
    bmCtrlsSupported[CAM_BMCONTROLS_INDEX] = 0x00000000;
    bmCtrlsSupported[EU_BMCONTROLS_INDEX] = 0x00000001;

    //mapProcUnitCtrl[0]=;
    //procUnitCtrlsVal array Description
    //its row index specifies the control which is supported by processing unit
    //its col index specifies the values supported by processing unit control for min, max,default ,etc
    //0-brightness
    //1-contrast
    //2-hue
    //3-saturation
    //4-sharpness
    //5-gamma
    procUnitCtrlsVal[0][GET_DEF_VAL_INDEX] = 20;
    procUnitCtrlsVal[0][GET_INFO_VAL_INDEX] = 5;
    procUnitCtrlsVal[0][GET_MAX_VAL_INDEX] = 20;
    procUnitCtrlsVal[0][GET_RES_VAL_INDEX] = 20;
    procUnitCtrlsVal[0][GET_MIN_VAL_INDEX] = 20;
    procUnitCtrlsVal[0][GET_CUR_VAL_INDEX] = 20;
    ///*
    //3-contrast
    procUnitCtrlsVal[PU_CONTRAST_CONTROL][GET_DEF_VAL_INDEX] = 0x14;
    procUnitCtrlsVal[PU_CONTRAST_CONTROL][GET_INFO_VAL_INDEX] = 0x5;
    procUnitCtrlsVal[PU_CONTRAST_CONTROL][GET_MAX_VAL_INDEX] = 0x16;
    procUnitCtrlsVal[PU_CONTRAST_CONTROL][GET_RES_VAL_INDEX] = 0x1;
    procUnitCtrlsVal[PU_CONTRAST_CONTROL][GET_MIN_VAL_INDEX] = 0x14;
    procUnitCtrlsVal[PU_CONTRAST_CONTROL][GET_CUR_VAL_INDEX] = 0x14;
    //1-BackLightCompensation
    procUnitCtrlsVal[PU_BACKLIGHT_COMPENSATION_CONTROL][GET_DEF_VAL_INDEX] = 1;
    procUnitCtrlsVal[PU_BACKLIGHT_COMPENSATION_CONTROL][GET_INFO_VAL_INDEX] =
            0x5;
    procUnitCtrlsVal[PU_BACKLIGHT_COMPENSATION_CONTROL][GET_MAX_VAL_INDEX] = 1;
    procUnitCtrlsVal[PU_BACKLIGHT_COMPENSATION_CONTROL][GET_RES_VAL_INDEX] = 1;
    procUnitCtrlsVal[PU_BACKLIGHT_COMPENSATION_CONTROL][GET_MIN_VAL_INDEX] = 1;
    procUnitCtrlsVal[PU_BACKLIGHT_COMPENSATION_CONTROL][GET_CUR_VAL_INDEX] = 1;
    //2-Brightness
    procUnitCtrlsVal[PU_BRIGHTNESS_CONTROL][GET_DEF_VAL_INDEX] = 0x14;
    procUnitCtrlsVal[PU_BRIGHTNESS_CONTROL][GET_INFO_VAL_INDEX] = 0x5;
    procUnitCtrlsVal[PU_BRIGHTNESS_CONTROL][GET_MAX_VAL_INDEX] = 0x7c;
    procUnitCtrlsVal[PU_BRIGHTNESS_CONTROL][GET_RES_VAL_INDEX] = 0x01;
    procUnitCtrlsVal[PU_BRIGHTNESS_CONTROL][GET_MIN_VAL_INDEX] = 0x14;
    procUnitCtrlsVal[PU_BRIGHTNESS_CONTROL][GET_CUR_VAL_INDEX] = 0x14;
    //*/
    //9-Gamma
    procUnitCtrlsVal[PU_GAMMA_CONTROL][GET_DEF_VAL_INDEX] = 0x60;
    procUnitCtrlsVal[PU_GAMMA_CONTROL][GET_INFO_VAL_INDEX] = 0x5;
    procUnitCtrlsVal[PU_GAMMA_CONTROL][GET_MAX_VAL_INDEX] = 0x64;
    procUnitCtrlsVal[PU_GAMMA_CONTROL][GET_RES_VAL_INDEX] = 0x01;
    procUnitCtrlsVal[PU_GAMMA_CONTROL][GET_MIN_VAL_INDEX] = 0x60;
    procUnitCtrlsVal[PU_GAMMA_CONTROL][GET_CUR_VAL_INDEX] = 0x60;
    ///*
    //4-Gain
    procUnitCtrlsVal[PU_GAIN_CONTROL][GET_DEF_VAL_INDEX] = 18;
    procUnitCtrlsVal[PU_GAIN_CONTROL][GET_INFO_VAL_INDEX] = 0x5;
    procUnitCtrlsVal[PU_GAIN_CONTROL][GET_MAX_VAL_INDEX] = 18;
    procUnitCtrlsVal[PU_GAIN_CONTROL][GET_RES_VAL_INDEX] = 1;
    procUnitCtrlsVal[PU_GAIN_CONTROL][GET_MIN_VAL_INDEX] = 1;
    procUnitCtrlsVal[PU_GAIN_CONTROL][GET_CUR_VAL_INDEX] = 18;
    //*/
    ///*
    //7-saturation
    procUnitCtrlsVal[PU_SATURATION_CONTROL][GET_DEF_VAL_INDEX] = 0x6;
    procUnitCtrlsVal[PU_SATURATION_CONTROL][GET_INFO_VAL_INDEX] = 0x5;
    procUnitCtrlsVal[PU_SATURATION_CONTROL][GET_MAX_VAL_INDEX] = 0x10;
    procUnitCtrlsVal[PU_SATURATION_CONTROL][GET_RES_VAL_INDEX] = 0x1;//RES value must always be 1 as per UVC specifications
    procUnitCtrlsVal[PU_SATURATION_CONTROL][GET_MIN_VAL_INDEX] = 0x6;
    procUnitCtrlsVal[PU_SATURATION_CONTROL][GET_CUR_VAL_INDEX] = 0x6;
    //6-hue
    procUnitCtrlsVal[PU_HUE_CONTROL][GET_DEF_VAL_INDEX] = 0x2;
    procUnitCtrlsVal[PU_HUE_CONTROL][GET_INFO_VAL_INDEX] = 0x5;
    procUnitCtrlsVal[PU_HUE_CONTROL][GET_MAX_VAL_INDEX] = 0x4;
    procUnitCtrlsVal[PU_HUE_CONTROL][GET_RES_VAL_INDEX] = 0x1;
    procUnitCtrlsVal[PU_HUE_CONTROL][GET_MIN_VAL_INDEX] = 0x2;
    procUnitCtrlsVal[PU_HUE_CONTROL][GET_CUR_VAL_INDEX] = 0x2;
    //8-sharpness
    procUnitCtrlsVal[PU_SHARPNESS_CONTROL][GET_DEF_VAL_INDEX] = 0x28;
    procUnitCtrlsVal[PU_SHARPNESS_CONTROL][GET_INFO_VAL_INDEX] = 0x5;
    procUnitCtrlsVal[PU_SHARPNESS_CONTROL][GET_MAX_VAL_INDEX] = 0x2A;
    procUnitCtrlsVal[PU_SHARPNESS_CONTROL][GET_RES_VAL_INDEX] = 0x01;
    procUnitCtrlsVal[PU_SHARPNESS_CONTROL][GET_MIN_VAL_INDEX] = 0x28;
    procUnitCtrlsVal[PU_SHARPNESS_CONTROL][GET_CUR_VAL_INDEX] = 0x28;


    ExtenUnitCtrlsVal[0][GET_DEF_VAL_INDEX] = 0x0;
    ExtenUnitCtrlsVal[0][GET_INFO_VAL_INDEX] =  0x0;
    ExtenUnitCtrlsVal[0][GET_MAX_VAL_INDEX] =  0x0;
    ExtenUnitCtrlsVal[0][GET_RES_VAL_INDEX] =  0x0;
    ExtenUnitCtrlsVal[0][GET_MIN_VAL_INDEX] =  0x0;
    ExtenUnitCtrlsVal[0][GET_CUR_VAL_INDEX] =  0x0;
}

/** @} */
