// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// --------------------------------------------------------------------------
// Copyright (c) 2019-2024 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// --------------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT,SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE.
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// --------------------------------------------------------------------------

/****************************************************************************/
/**
 *
 * @file lsc_ccm_reg.h
 * @addtogroup lscusb Overview
 * @{
 *
 *
 *
 *****************************************************************************/

#ifndef U3V_LSC_CCM_REG_H_
#define U3V_LSC_CCM_REG_H_

// CCM lattice IP core register set
// We are left shifting the offset by 2 (multiply by 4), for word offset
#define CCM_CONTROL          (0x00)
#define CONFIGURATION_UPDATE (0x01 << 2)
#define TRANSLATION_R        (0x02 << 2)
#define TRANSLATION_G        (0x03 << 2)
#define TRANSLATION_B        (0x04 << 2)
#define MRR                  (0x05 << 2)
#define MRG                  (0x06 << 2)
#define MRB                  (0x07 << 2)
#define MGR                  (0x08 << 2)
#define MGG                  (0x09 << 2)
#define MGB                  (0x0A << 2)
#define MBR                  (0x0B << 2)
#define MBG                  (0x0C << 2)
#define MBB                  (0x0D << 2)
#define LINE_QUERY_ADDR      (0x0E << 2)
#define PIXEL_QUERY_ADDR     (0x0F << 2)
#define PIXEL_RED_ADDR       (0x10 << 2)
#define PIXEL_GREEN_ADDR     (0x11 << 2)
#define PIXEL_BLUE_ADDR      (0x12 << 2)

//IMP Note: CCM UG has incorrect value for enable/disable.
#define CCM_ENABLE           0x1
#define CCM_DISABLE          0x0

//For the nine matrix coefficients MRR to MBB, the user has to multiply the coefficient
//values by 32768 and use the integer part when configuring the CSR dynamically.
//For example, for an MRR=0.87, the user must give 28508 (0.87*32768=28508.16)
#define GET_CCM_COEFF_INT(n) (n*32768)/100  //Value of n must be [-99 to +99]

//Value of Following nine matrix coefficients MRR to MBB must be in range of [-99 to +99]
#define MRR_VALUE            95
#define MRG_VALUE            0
#define MRB_VALUE            -5
#define MGR_VALUE            0
#define MGG_VALUE            60
#define MGB_VALUE            0
#define MBR_VALUE            0
#define MBG_VALUE            0
#define MBB_VALUE            90


#define TRANSLATION_R_VALUE  0
#define TRANSLATION_G_VALUE  0
#define TRANSLATION_B_VALUE  0

uint8_t lsc_ccm_init(uint32_t);

#endif /* U3V_LSC_CCM_REG_H_ */
/** @} */