    usb_bus_interface_bridge __(.lmmi_rdata_o( ),
        .lmmi_rdata_valid_o( ),
        .lmmi_ready_o( ),
        .lmmi_request_i( ),
        .lmmi_wr_rdn_i( ),
        .lmmi_offset_i( ),
        .lmmi_wdata_i( ),
        .LMMIRDATA( ),
        .LMMIRDATAVALID( ),
        .LMMIREADY( ),
        .LMMIREQUEST( ),
        .LMMIWRRD_N( ),
        .LMMIOFFSET( ),
        .LMMIWDATA( ),
        .INTERRUPT( ),
        .RISCV_USB_INTERRUPT( ));
