/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2026.1.0.2606162255
    Soft IP Version: 3.2.0
    2026 07 21 09:05:01
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module usb23_ip (USBPHY_REFCLK_ALT_i, USB_SUSPENDCLK_i, REFINCLKEXTP_i,
    REFINCLKEXTM_i, XOIN18_i, XOOUT18_o, USB3_SYSRSTN_i, USB_RESETN_i,
    USB2_RESET_i, usb23_DP, usb23_DM, RXM_i, RXP_i, TXM_o, TXP_o, lmmi_clk_i,
    lmmi_rst_n_i, lmmi_request_i, lmmi_wr_rdn_i, lmmi_offset_i, lmmi_wdata_i,
    lmmi_rdata_o, lmmi_rdata_valid_o, lmmi_ready_o, xm_awready_i, xm_wready_i,
    xm_bid_i, xm_bvalid_i, xm_bresp_i, xm_bmisc_info_i, xm_arready_i, xm_rid_i,
    xm_rvalid_i, xm_rlast_i, xm_rdata_i, xm_rresp_i, xm_rmisc_info_i,
    xm_awid_o, xm_awaddr_o, xm_awlen_o, xm_awsize_o, xm_awburst_o,
    xm_awcache_o, xm_awprot_o, xm_awvalid_o, xm_awlock_o, xm_awmisc_info_o,
    xm_wvalid_o, xm_wlast_o, xm_wdata_o, xm_wid_o, xm_wstrb_o, xm_bready_o,
    xm_arid_o, xm_arvalid_o, xm_araddr_o, xm_arlen_o, xm_arsize_o,
    xm_arburst_o, xm_arcache_o, xm_arprot_o, xm_armisc_info_o, xm_arlock_o,
    xm_rready_o, interrupt_o, VBUS_i, RESEXTUSB2, RESEXTUSB3, USB3_MCUCLK_i)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  USBPHY_REFCLK_ALT_i;
    input  USB_SUSPENDCLK_i;
    input  REFINCLKEXTP_i;
    input  REFINCLKEXTM_i;
    input  XOIN18_i;
    output  XOOUT18_o;
    input  USB3_SYSRSTN_i;
    input  USB_RESETN_i;
    input  USB2_RESET_i;
    inout  usb23_DP;
    inout  usb23_DM;
    input  RXM_i;
    input  RXP_i;
    output  TXM_o;
    output  TXP_o;
    input  lmmi_clk_i;
    input  lmmi_rst_n_i;
    input  lmmi_request_i;
    input  lmmi_wr_rdn_i;
    input  [14:0]  lmmi_offset_i;
    input  [31:0]  lmmi_wdata_i;
    output  [31:0]  lmmi_rdata_o;
    output  lmmi_rdata_valid_o;
    output  lmmi_ready_o;
    input  xm_awready_i;
    input  xm_wready_i;
    input  [7:0]  xm_bid_i;
    input  xm_bvalid_i;
    input  [1:0]  xm_bresp_i;
    input  [3:0]  xm_bmisc_info_i;
    input  xm_arready_i;
    input  [7:0]  xm_rid_i;
    input  xm_rvalid_i;
    input  xm_rlast_i;
    input  [63:0]  xm_rdata_i;
    input  [1:0]  xm_rresp_i;
    input  [3:0]  xm_rmisc_info_i;
    output  [7:0]  xm_awid_o;
    output  [31:0]  xm_awaddr_o;
    output  [7:0]  xm_awlen_o;
    output  [2:0]  xm_awsize_o;
    output  [1:0]  xm_awburst_o;
    output  [3:0]  xm_awcache_o;
    output  [2:0]  xm_awprot_o;
    output  xm_awvalid_o;
    output  [1:0]  xm_awlock_o;
    output  [3:0]  xm_awmisc_info_o;
    output  xm_wvalid_o;
    output  xm_wlast_o;
    output  [63:0]  xm_wdata_o;
    output  [7:0]  xm_wid_o;
    output  [7:0]  xm_wstrb_o;
    output  xm_bready_o;
    output  [7:0]  xm_arid_o;
    output  xm_arvalid_o;
    output  [31:0]  xm_araddr_o;
    output  [7:0]  xm_arlen_o;
    output  [2:0]  xm_arsize_o;
    output  [1:0]  xm_arburst_o;
    output  [3:0]  xm_arcache_o;
    output  [2:0]  xm_arprot_o;
    output  [3:0]  xm_armisc_info_o;
    output  [1:0]  xm_arlock_o;
    output  xm_rready_o;
    output  interrupt_o;
    inout  VBUS_i;
    inout  RESEXTUSB2;
    inout  RESEXTUSB3;
    input  USB3_MCUCLK_i;
endmodule