/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.0.0.0
    2026 02 28 19:29:37
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module ahbl_to_mem_inst (clk, reset_n, haddr_i, hburst_i, hmastlock_i, hprot_i,
    hready_i, hsel_i, hsize_i, htrans_i, hwdata_i, hwrite_i, hrdata_o,
    hready_o, hresp_o, avm_wait_req_i, avm_rd_data_valid_pl_i, avm_rd_data_i,
    avm_addr_32_o, avm_wr_req_o, avm_rd_req_o, avm_wr_data_o, avm_wr_byte_en_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  reset_n;
    input  [13:0]  haddr_i;
    input  [2:0]  hburst_i;
    input  hmastlock_i;
    input  [3:0]  hprot_i;
    input  hready_i;
    input  hsel_i;
    input  [2:0]  hsize_i;
    input  [1:0]  htrans_i;
    input  [31:0]  hwdata_i;
    input  hwrite_i;
    output  [31:0]  hrdata_o;
    output  hready_o;
    output  hresp_o;
    input  avm_wait_req_i;
    input  avm_rd_data_valid_pl_i;
    input  [31:0]  avm_rd_data_i;
    output  [11:0]  avm_addr_32_o;
    output  avm_wr_req_o;
    output  avm_rd_req_o;
    output  [31:0]  avm_wr_data_o;
    output  [3:0]  avm_wr_byte_en_o;
endmodule