
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.0.0.0
    2026 02 28 19:29:37
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="ahbl_to_mem_inst", LATTICE_IP_GENERATED="1" *) module ahbl_to_mem_inst (clk, 
        reset_n, 
        haddr_i, 
        hburst_i, 
        hmastlock_i, 
        hprot_i, 
        hready_i, 
        hsel_i, 
        hsize_i, 
        htrans_i, 
        hwdata_i, 
        hwrite_i, 
        hrdata_o, 
        hready_o, 
        hresp_o, 
        avm_wait_req_i, 
        avm_rd_data_valid_pl_i, 
        avm_rd_data_i, 
        avm_addr_32_o, 
        avm_wr_req_o, 
        avm_rd_req_o, 
        avm_wr_data_o, 
        avm_wr_byte_en_o) ;
    input clk ; 
    input reset_n ; 
    input [13:0] haddr_i ; 
    input [2:0] hburst_i ; 
    input hmastlock_i ; 
    input [3:0] hprot_i ; 
    input hready_i ; 
    input hsel_i ; 
    input [2:0] hsize_i ; 
    input [1:0] htrans_i ; 
    input [31:0] hwdata_i ; 
    input hwrite_i ; 
    output [31:0] hrdata_o ; 
    output hready_o ; 
    output hresp_o ; 
    input avm_wait_req_i ; 
    input avm_rd_data_valid_pl_i ; 
    input [31:0] avm_rd_data_i ; 
    output [11:0] avm_addr_32_o ; 
    output avm_wr_req_o ; 
    output avm_rd_req_o ; 
    output [31:0] avm_wr_data_o ; 
    output [3:0] avm_wr_byte_en_o ; 
    ahbl_to_mem_inst_ipgen_ahbl_to_mem_bridge #(.DATA_WIDTH_I(32),
            .ADDR_WIDTH_I(14),
            .AVM_BYTE_EN_WIDTH_I(4)) ahbl_to_mem_bridge_inst (.clk(clk), 
                .reset_n(reset_n), 
                .haddr_i(haddr_i[13:0]), 
                .hburst_i(hburst_i[2:0]), 
                .hmastlock_i(hmastlock_i), 
                .hprot_i(hprot_i[3:0]), 
                .hready_i(hready_i), 
                .hsel_i(hsel_i), 
                .hsize_i(hsize_i[2:0]), 
                .htrans_i(htrans_i[1:0]), 
                .hwdata_i(hwdata_i[31:0]), 
                .hwrite_i(hwrite_i), 
                .hrdata_o(hrdata_o[31:0]), 
                .hready_o(hready_o), 
                .hresp_o(hresp_o), 
                .avm_wait_req_i(avm_wait_req_i), 
                .avm_rd_data_valid_pl_i(avm_rd_data_valid_pl_i), 
                .avm_rd_data_i(avm_rd_data_i[31:0]), 
                .avm_addr_32_o(avm_addr_32_o[11:0]), 
                .avm_wr_req_o(avm_wr_req_o), 
                .avm_rd_req_o(avm_rd_req_o), 
                .avm_wr_data_o(avm_wr_data_o[31:0]), 
                .avm_wr_byte_en_o(avm_wr_byte_en_o[3:0])) ; 
endmodule



// =============================================================================
//                           COPYRIGHT NOTICE
// Copyright 2024 (c) Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// This confidential and proprietary software may be used only as authorized by
// a licensing agreement from Lattice Semiconductor Corporation.
// The entire notice above must be reproduced on all authorized copies and
// copies may only be made to the extent permitted by a licensing agreement from
// Lattice Semiconductor Corporation.
//
// Lattice Semiconductor Corporation        TEL : 1-800-Lattice (USA and Canada)
// 5555 NE Moore Court                            408-826-6000 (other locations)
// Hillsboro, OR 97124                     web  : http://www.latticesemi.com/
// U.S.A                                   email: techsupport@lscc.com
// =============================================================================
//-F I L E D E T A I L S-------------------------------------------------------
// Description  : this is a ahb-lite to memory interface bridge module
//
//-----------------------------------------------------------------------------
module ahbl_to_mem_inst_ipgen_ahbl_to_mem_bridge #(parameter AVM_READ_LATENCY_TYPE_I = "FIX", 
        parameter AVM_WAIT_REQ_AUTO_MANAGE_I = "YES", 
        parameter DATA_WIDTH_I = 32, 
        parameter ADDR_WIDTH_I = 14, 
        parameter AVM_RD_WAIT_TIME_I = 0, 
        parameter AVM_RD_LATENCY_I = 1, 
        parameter AVM_WR_WAIT_TIME_I = 0, 
        parameter AVM_BYTE_EN_WIDTH_I = (DATA_WIDTH_I / 8)) (
    // Read latency type
    // Read latency type is managed by this module.
    // Possible Values - "FIX" or "VARIABLE"
    // "FIX" = fixed read latency
    // "VARIABLE" = variable read latency
    // Wait Request Manager.
    // Wait Request signal is managed by this module. If Avalon Slave does not
    // export this signal, this module will manage it. But for that, it requires
    // some parameters listed below.
    // Possible Values - "YES" or "NO"
    // Data Width of Master and slave is same.
    // Possible Values - 32 bits.
    // Address Width of Master and slave is same..
    // Possible Values - 32 bits.
    // Read Wait States.
    // Number of clocks required to accept the read request.
    // Possible Values - 0, 1, 2..
    // Read Latency.
    // Number of clocks required to deliver the read data after accepting the read request.
    // Possible Values - 1, 2..
    // Write Wait States.
    // Number of clocks required to accept the write request.
    // Possible Values - 0, 1, 2..
    // Byte Enable Width of Master.
    input wire clk, 
    input wire reset_n, 
    // AHB-Lite master signals
    input wire [(ADDR_WIDTH_I - 1):0] haddr_i, 
    input wire [2:0] hburst_i, 
    input wire hmastlock_i,  //not used
    input wire [3:0] hprot_i,  //not used
    input wire hready_i, 
    input wire hsel_i, 
    input wire [2:0] hsize_i, 
    input wire [1:0] htrans_i, 
    input wire [(DATA_WIDTH_I - 1):0] hwdata_i, 
    input wire hwrite_i, 
    output wire [(DATA_WIDTH_I - 1):0] hrdata_o, 
    output reg hready_o, 
    output wire hresp_o, 
    // Avalon IO Signals
    input wire avm_wait_req_i, 
    input wire avm_rd_data_valid_pl_i, 
    input wire [(DATA_WIDTH_I - 1):0] avm_rd_data_i, 
    output reg [((ADDR_WIDTH_I - 2) - 1):0] avm_addr_32_o,  // ADDR_WIDTH_I is in terms of byte offset. Hence, we subtracted 2 to get 32 bits word offset.
    output reg avm_wr_req_o, 
    output reg avm_rd_req_o, 
    output wire [(DATA_WIDTH_I - 1):0] avm_wr_data_o, 
    output reg [(AVM_BYTE_EN_WIDTH_I - 1):0] avm_wr_byte_en_o) ;
    // Local variable
    wire hwrite_pl ; // write pulse if hwrite_i is high and htrans is non sequential.
    wire hread_pl ; // read pulse if hwrite_i is low and htrans is non sequential.
    reg avm_rd_data_valid_pl ; // avalon read data valid
    wire wr_wait_req ; 
    wire rd_wait_req ; 
    wire wr_req_cmplt ; 
    reg [(DATA_WIDTH_I - 1):0] avm_rd_data ; 
    // Local Parameter
    // Read/Write Wait State Counter Width For MASTER
    localparam WS_CNTR_WIDTH = $clog2(((AVM_WR_WAIT_TIME_I > AVM_RD_WAIT_TIME_I) ? AVM_WR_WAIT_TIME_I : AVM_RD_WAIT_TIME_I)) ; 
    // Read Latency Counter Width For MASTER
    localparam RL_CNTR_WIDTH = $clog2(AVM_RD_LATENCY_I) ; 
    // simulation purpose
    localparam UD = 1 ; 
    assign hwrite_pl = (((hwrite_i & hsel_i) & hready_i) & ((htrans_i == 2'b10) | (htrans_i == 2'b11))) ; 
    assign hread_pl = ((((~hwrite_i) & hsel_i) & hready_i) & ((htrans_i == 2'b10) | (htrans_i == 2'b11))) ; 
    // AHB Response
    assign hresp_o = 1'b0 ; //always okay response
    // Avalon master address
    always
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    avm_addr_32_o <= #(UD)   1'h0 ;
                end
            else
                if ((hwrite_pl | hread_pl)) 
                    begin
                        avm_addr_32_o <= #(UD)   haddr_i[(ADDR_WIDTH_I - 1):2] ;// Word offset addressing
                    end
        end
    //Avalon byte enable signals
    always
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    avm_wr_byte_en_o <= #(UD)   1'h0 ;
                end
            else
                if ((hwrite_pl | hread_pl)) 
                    begin
                        case ({haddr_i[1:0],
                                hsize_i})
                        5'b00000 : 
                            avm_wr_byte_en_o <= #(UD)   4'b0001 ;
                        5'b01000 : 
                            avm_wr_byte_en_o <= #(UD)   4'b0010 ;
                        5'b10000 : 
                            avm_wr_byte_en_o <= #(UD)   4'b0100 ;
                        5'b11000 : 
                            avm_wr_byte_en_o <= #(UD)   4'b1000 ;
                        5'b00001 : 
                            avm_wr_byte_en_o <= #(UD)   4'b0011 ;
                        5'b10001 : 
                            avm_wr_byte_en_o <= #(UD)   4'b1100 ;
                        5'b00010 : 
                            avm_wr_byte_en_o <= #(UD)   4'b1111 ;
                        endcase 
                    end
        end
    // ----------------------------------------------------------------------------
    // Wait state management
    // ----------------------------------------------------------------------------
    // separete wait request for read and write.
    generate
        if ((AVM_WAIT_REQ_AUTO_MANAGE_I == "YES")) 
            begin : AUTO_MANAGE
                reg [WS_CNTR_WIDTH:0] ws_cntr ; 
                // Wait State counter
                // Counter to count the number of wait states.
                always
                    @(posedge clk or 
                        negedge reset_n)
                    begin
                        if ((~reset_n)) 
                            begin
                                ws_cntr <= #(UD)   1'b0 ;
                            end
                        else
                            if ((avm_rd_req_o | avm_wr_req_o)) 
                                begin
                                    ws_cntr <= #(UD)   (ws_cntr + 1'b1) ;
                                end
                            else
                                begin
                                    ws_cntr <= #(UD)   1'b0 ;
                                end
                    end// always @ ( posedge clk or negedge reset_n )
                // Write wait request
                // Shall be used only with wr_req_o
                assign wr_wait_req = ((AVM_WR_WAIT_TIME_I == 0) ? 1'b0 : (ws_cntr != AVM_WR_WAIT_TIME_I)) ; 
                // Read wait request
                // Shall be used only with rd_req_o
                assign rd_wait_req = ((AVM_RD_WAIT_TIME_I == 0) ? 1'b0 : (ws_cntr != AVM_RD_WAIT_TIME_I)) ; 
            end
        else
            begin : genblk1
                // ---------------------------------------------
                // following incase wait request is coming.
                // ---------------------------------------------
                // Write wait request
                // Shall be used only with wr_req_o
                assign wr_wait_req = avm_wait_req_i ; 
                // Read wait request
                // Shall be used only with rd_req_o
                assign rd_wait_req = avm_wait_req_i ; 
            end
    endgenerate
    //-  .  -- ..  --- ... ---- ....
    //
    // Read Latency Management
    //
    //-  .  -- ..  --- ... ---- ....
    generate
        if ((AVM_READ_LATENCY_TYPE_I == "VARIABLE")) 
            begin : VAR_LATENCY
                // Read data valid signal
                always
                    @(*)
                    begin
                        avm_rd_data_valid_pl <=  avm_rd_data_valid_pl_i ;
                    end
            end
        else
            if ((AVM_RD_LATENCY_I == 1'b0)) 
                begin : ZERO_LATENCY
                    always
                        @(posedge clk or 
                            negedge reset_n)
                        begin
                            if ((~reset_n)) 
                                begin
                                    avm_rd_data_valid_pl <= #(UD)   1'b0 ;
                                end
                            else
                                begin
                                    avm_rd_data_valid_pl <= #(UD)   ((avm_rd_req_o == 1'b1) & (rd_wait_req == 1'b0)) ;
                                end
                        end// always @ ( posedge clk or negedge reset_n )
                end
            else
                begin : NONZERO_LATENCY
                    // Local Variables
                    reg [RL_CNTR_WIDTH:0] rl_cntr ; 
                    // Latency Counter
                    always
                        @(posedge clk or 
                            negedge reset_n)
                        begin
                            if ((~reset_n)) 
                                begin
                                    rl_cntr <= #(UD)   1'b0 ;
                                end
                            else
                                if ((rl_cntr == AVM_RD_LATENCY_I)) 
                                    // Higher Priority
                                    begin
                                        rl_cntr <= #(UD)   1'b0 ;
                                    end
                                else
                                    if ((((avm_rd_req_o == 1'b1) & (rd_wait_req == 1'b0)) | (rl_cntr != 1'b0))) 
                                        begin
                                            rl_cntr <= #(UD)   (rl_cntr + 1'b1) ;
                                        end
                        end
                    // -------------------------------
                    // Read data valid
                    // -------------------------------
                    always
                        @(posedge clk or 
                            negedge reset_n)
                        begin
                            if ((~reset_n)) 
                                begin
                                    avm_rd_data_valid_pl <= #(UD)   1'b0 ;
                                end
                            else
                                begin
                                    avm_rd_data_valid_pl <= #(UD)   (rl_cntr == AVM_RD_LATENCY_I) ;
                                end
                        end// always @ ( posedge clk or negedge reset_n )
                end
    endgenerate
    assign wr_req_cmplt = ((avm_wr_req_o == 1'b1) & (wr_wait_req == 1'b0)) ; 
    // hready_o signal
    always
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    hready_o <= #(UD)   1'b1 ;
                end
            else
                if ((hread_pl | (hwrite_pl & wr_wait_req))) 
                    begin
                        hready_o <= #(UD)   1'b0 ;
                    end
                else
                    if ((avm_rd_data_valid_pl | wr_req_cmplt)) 
                        begin
                            hready_o <= #(UD)   1'b1 ;
                        end
        end
    // Avalon read request
    always
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    avm_rd_req_o <=  1'b0 ;
                end
            else
                if (hread_pl) 
                    // High priority
                    begin
                        avm_rd_req_o <=  1'b1 ;
                    end
                else
                    if ((rd_wait_req == 1'b0)) 
                        begin
                            avm_rd_req_o <=  1'b0 ;
                        end
        end
    // Avalon write request
    always
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    avm_wr_req_o <=  1'b0 ;
                end
            else
                if (hwrite_pl) 
                    // High priority
                    begin
                        avm_wr_req_o <=  1'b1 ;
                    end
                else
                    if ((wr_wait_req == 1'b0)) 
                        begin
                            avm_wr_req_o <=  1'b0 ;
                        end
        end
    // Avalon write data out
    assign avm_wr_data_o = hwdata_i ; 
    // AHB read data out
    always
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((~reset_n)) 
                begin
                    avm_rd_data <= #(UD)   1'h0 ;
                end
            else
                begin
                    avm_rd_data <=  avm_rd_data_i ;
                end
        end
    assign hrdata_o = avm_rd_data ; 
endmodule


