// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// --------------------------------------------------------------------------
// Copyright (c) 2019-2024 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// --------------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL™
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT,SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE.
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// --------------------------------------------------------------------------

/****************************************************************************/
/**
 *
 * @file lsc_usb_desc.h
 * @addtogroup lscusb Overview
 * @{
 *
 *
 *
 *****************************************************************************/

#ifndef LSC_USB_DESC_H_
#define LSC_USB_DESC_H_

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files ********************************/
#include "lsc_usb_ch9.h"
#include "lsc_winsub.h"
#include "uvc/lsc_uvc.h"

/************************** Constant Definitions ****************************/
#define USB20_BCD       0x0210  /**< USB20 BCD Value. */
#define USB3_BCD        0x0320  /**< USB30 BCD Value. */
#define USB_VID         0x2AC1  /**< Lattice Vendor ID. */
#define USB_PID         0xFD00  /**< Lattice Product ID. */

#define USB_MAX_PACKET0_SS 9    /**< Control endpoint's max packet size for USB 3.0. */
#define USB_MAX_PACKET0_HS 64   /**< Control endpoint's max packet size for USB 2.0. */

#define BCD_DEV         0x0010  /**< USB BCD Value. */

/**
 *  @brief bmAttributes in Configuration Descriptor
 *   common for hi-speed and superspeed
 */
#define USB_CONFIG_POWERED_MASK                0xC0
#define USB_CONFIG_BUS_POWERED                 0x80 // Reserved bit (bit 1) must be 1 according to spec.
#define USB_CONFIG_SELF_POWERED                0xC0 // Reserved bit (bit 1) must be 1 according to spec.
#define USB_CONFIG_REMOTE_WAKEUP               0x20

#define NUM_OF_ENDPOINT     0x2 /**< Number of Endpoints in Device Configuration. */

/************************** TypeDef Definitions *****************************/
/**
 *  @brief USB20 Device Descriptor Data.
 */
USB_STD_DEV_DESC __attribute__ ((aligned(4))) u20_device_desc = {
        sizeof(USB_STD_DEV_DESC), /* bLength */
        USB_TYPE_DEVICE_DESC, /* bDescriptorType */
        USB20_BCD, /* bcdUSB */
        USB_CLASS_MISC, /* bDeviceClass */
        USB_SUBCLASS_COMMON, /* bDeviceSubClass */
        USB_PROTOCOL_IAD, /* bDeviceProtocol */
        USB_MAX_PACKET0_HS, /* bMaxPacketSize0 */
        USB_VID, /* idVendor */
        USB_PID, /* idProduct */
        BCD_DEV, /* bcdDevice */
        0x01, /* iManufacturer */
        0x02, /* iProduct */
        0x03, /* iSerialNumber */
        0x01 /* bNumConfigurations */
};

/**
 *  @brief USB30 Device Descriptor Data.
 */
USB_STD_DEV_DESC __attribute__ ((aligned(4))) u30_device_desc = {
        sizeof(USB_STD_DEV_DESC), /* bLength */
        USB_TYPE_DEVICE_DESC, /* bDescriptorType */
        USB3_BCD, /* bcdUSB */
        USB_CLASS_MISC, /* bDeviceClass */
        USB_SUBCLASS_COMMON, /* bDeviceSubClass */
        USB_PROTOCOL_IAD, /* bDeviceProtocol */
        USB_MAX_PACKET0_SS, /* bMaxPacketSize0 */
        USB_VID, /* idVendor */
        USB_PID, /* idProduct */
        BCD_DEV, /* bcdDevice */
        0x01, /* iManufacturer */
        0x02, /* iProduct */
        0x03, /* iSerialNumber */
        0x01 /* bNumConfigurations */
};

/**
 *  @brief USB20 High Speed Configuration Descriptor Data.
 */
//LSC_USB20_CFG_DESC __attribute__ ((aligned(4))) u20_config_desc_hs = {{
////Standard Configuration Descriptor
//        sizeof(USB_STD_CFG_DESC), /* bLength */
//        USB_TYPE_CONFIG_DESC, /* bDescriptorType */
//        sizeof(LSC_USB20_CFG_DESC), /* wTotalLength */
//        0x01, /* bNumInterfaces */
//        0x01, /* bConfigurationValue */
//        0x00, /* iConfiguration */
//        (USB_CONFIG_SELF_POWERED | USB_CONFIG_REMOTE_WAKEUP), /* bmAttribute */
//        0x32 /* bMaxPower  */
//},
//
//{
////Standard Interface Descriptor
//        sizeof(USB_STD_IF_DESC), /* bLength */
//        USB_TYPE_INTERFACE_DESC, /* bDescriptorType */
//        0x00, /* bInterfaceNumber */
//        0x00, /* bAlternateSetting */
//        NUM_OF_ENDPOINT, /* bNumEndPoints */
//        0xFF, /* bInterfaceClass */
//        0x00, /* bInterfaceSubClass */
//        0xFF, /* bInterfaceProtocol */
//        0x00 /* iInterface */
//},
//
//{
////Bulk In Endpoint Descriptor
//        sizeof(USB_STD_EP_DESC), /* bLength */
//        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
//        0x81, /* bEndpointAddress */
//        USB_EP_BULK, /* bmAttribute  */
//        0x0200, /* wMaxPacketSize */
//        0x01, /* bInterval */
//},
//
//{
////Bulk Out Endpoint Descriptor
//        sizeof(USB_STD_EP_DESC), /* bLength */
//        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
//        0x02, /* bEndpointAddress */
//        USB_EP_BULK, /* bmAttribute  */
//        0x0200, /* wMaxPacketSize */
//        0x01 /* bInterval */
//}};

/**
 *  @brief USB20 Full Speed Configuration Descriptor Data.
 */
//LSC_USB20_CFG_DESC __attribute__ ((aligned(4))) u20_config_desc_fs = {{
////Standard Configuration Descriptor
//        sizeof(USB_STD_CFG_DESC), /* bLength */
//        USB_TYPE_CONFIG_DESC, /* bDescriptorType */
//        sizeof(LSC_USB20_CFG_DESC), /* wTotalLength */
//        0x01, /* bNumInterfaces */
//        0x01, /* bConfigurationValue */
//        0x00, /* iConfiguration */
//        (USB_CONFIG_SELF_POWERED | USB_CONFIG_REMOTE_WAKEUP), /* bmAttribute */
//        0x32 /* bMaxPower  */
//},
//
//{
////Standard Interface Descriptor
//        sizeof(USB_STD_IF_DESC), /* bLength */
//        USB_TYPE_INTERFACE_DESC, /* bDescriptorType */
//        0x00, /* bInterfaceNumber */
//        0x00, /* bAlternateSetting */
//        NUM_OF_ENDPOINT, /* bNumEndPoints */
//        0xFF, /* bInterfaceClass */
//        0x00, /* bInterfaceSubClass */
//        0xFF, /* bInterfaceProtocol */
//        0x00 /* iInterface */
//},
//
//{
////Bulk In Endpoint Descriptor
//        sizeof(USB_STD_EP_DESC), /* bLength */
//        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
//        0x81, /* bEndpointAddress */
//        USB_EP_BULK, /* bmAttribute  */
//        0x0040, /* wMaxPacketSize */
//        0x01, /* bInterval */
//},
//
//{
////Bulk Out Endpoint Descriptor
//        sizeof(USB_STD_EP_DESC), /* bLength */
//        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
//        0x02, /* bEndpointAddress */
//        USB_EP_BULK, /* bmAttribute  */
//        0x0040, /* wMaxPacketSize */
//        0x01 /* bInterval */
//}};

///**
// *  @brief USB30 Configuration Descriptor Data.
// */
//LSC_USB30_CFG_DESC __attribute__ ((aligned(4))) u30_config_desc = {{
////Standard Configuration Descriptor
//        sizeof(USB_STD_CFG_DESC), /* bLength */
//        USB_TYPE_CONFIG_DESC, /* bDescriptorType */
//        sizeof(LSC_USB30_CFG_DESC), /* wTotalLength */
//        0x01, /* bNumInterfaces */
//        0x01, /* bConfigurationValue */
//        0x00, /* iConfiguration */
//        USB_CONFIG_SELF_POWERED | USB_CONFIG_REMOTE_WAKEUP, /* bmAttribute */
//        0x00 /* bMaxPower  */
//},
//
//{
////Standard Interface Descriptor
//        sizeof(USB_STD_IF_DESC), /* bLength */
//        USB_TYPE_INTERFACE_DESC, /* bDescriptorType */
//        0x00, /* bInterfaceNumber */
//        0x00, /* bAlternateSetting */
//        NUM_OF_ENDPOINT, /* bNumEndPoints */
//        0xFF, /* bInterfaceClass */
//        0x00, /* bInterfaceSubClass */
//        0xFF, /* bInterfaceProtocol */
//        0x00 /* iInterface */
//},
//
//{
////Bulk In Endpoint Descriptor
//        sizeof(USB_STD_EP_DESC), /* bLength */
//        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
//        0x81, /* bEndpointAddress */
//        USB_EP_BULK, /* bmAttribute  */
//        0x0400, /* wMaxPacketSize */
//        0x01 /* bInterval */
//},
//
//{
////SS Endpoint Companion descriptor
//        sizeof(USB_STD_EP_SS_COMP_DESC),/* bLength */
//        USB_TYPE_ENDPOINT_CMP_DESC, /* bDescriptorType */
//        0x0F, /* bMaxBurst */
//        0x00, /* bmAttributes */
//        0x00 /* wBytesPerInterval */
//},
//
//{
////Bulk Out Endpoint Descriptor
//        sizeof(USB_STD_EP_DESC), /* bLength */
//        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
//        0x02, /* bEndpointAddress */
//        USB_EP_BULK, /* bmAttribute  */
//        0x0400, /* wMaxPacketSize */
//        0x01 /* bInterval */
//},
//
//{
////SS Endpoint Companion descriptor
//        sizeof(USB_STD_EP_SS_COMP_DESC),/* bLength */
//        USB_TYPE_ENDPOINT_CMP_DESC, /* bDescriptorType */
//        0x0F, /* bMaxBurst */
//        0x00, /* bmAttributes */
//        0x00 /* wBytesPerInterval */
//}, };

/**
 *  @brief Device Qualifier Descriptor Data.
 */
USB_STD_DEV_QUALIFIER_DESC __attribute__ ((aligned(4))) device_qual_desc = {
        sizeof(USB_STD_DEV_QUALIFIER_DESC), /* bLength */
        USB_TYPE_DEVICE_QUALIFIER, /* bDescriptorType */
        USB20_BCD, /* bcdUSB */
        USB_CLASS_MISC, /* bDeviceClass */
        USB_SUBCLASS_COMMON, /* bDeviceSubClass */
        USB_PROTOCOL_IAD, /* bDeviceProtocol */
        USB_MAX_PACKET0_HS, /* bMaxPacketSize0 */
        0x1, /* bNumConfiguration */
        0x0 /* bReserved */
};

/**
 *  @brief Other Speed High Speed Configuration Descriptor Data. This
 *   is returned while we are in full speed mode and we receive request for
 *   other speed configuration descriptor.
 */
LSC_USB20_CFG_DESC __attribute__ ((aligned(4))) u20_oth_speed_cfg_desc_hs = {{
//Standard Configuration Descriptor
        sizeof(USB_STD_CFG_DESC), /* bLength */
        OSD_TYPE_CONFIG_DESCR, /* bDescriptorType */
        sizeof(LSC_USB20_CFG_DESC), /* wTotalLength */
        0x01, /* bNumInterfaces */
        0x01, /* bConfigurationValue */
        0x00, /* iConfiguration */
        (USB_CONFIG_SELF_POWERED | USB_CONFIG_REMOTE_WAKEUP), /* bmAttribute */
        0x32 /* bMaxPower  */
},

{
//Standard Interface Descriptor
        sizeof(USB_STD_IF_DESC), /* bLength */
        USB_TYPE_INTERFACE_DESC, /* bDescriptorType */
        0x00, /* bInterfaceNumber */
        0x00, /* bAlternateSetting */
        NUM_OF_ENDPOINT, /* bNumEndPoints */
        0xFF, /* bInterfaceClass */
        0x00, /* bInterfaceSubClass */
        0xFF, /* bInterfaceProtocol */
        0x00 /* iInterface */
},

{
//Bulk In Endpoint Descriptor
        sizeof(USB_STD_EP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
        0x81, /* bEndpointAddress */
        USB_EP_BULK, /* bmAttribute  */
        0x0200, /* wMaxPacketSize */
        0x01 /* bInterval */
},

{
//Bulk Out Endpoint Descriptor
        sizeof(USB_STD_EP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
        0x01, /* bEndpointAddress */
        USB_EP_BULK, /* bmAttribute  */
        0x0200, /* wMaxPacketSize */
        0x01 /* bInterval */
}};

/**
 *  @brief Other Speed Full Speed Configuration Descriptor Data. This
 *   is returned while we are in high speed mode and we receive request for
 *   other speed configuration descriptor.
 */
LSC_USB20_CFG_DESC __attribute__ ((aligned(4))) u20_oth_speed_cfg_desc_fs = {{
//Standard Configuration Descriptor
        sizeof(USB_STD_CFG_DESC), /* bLength */
        OSD_TYPE_CONFIG_DESCR, /* bDescriptorType */
        sizeof(LSC_USB20_CFG_DESC), /* wTotalLength */
        0x01, /* bNumInterfaces */
        0x01, /* bConfigurationValue */
        0x00, /* iConfiguration */
        (USB_CONFIG_SELF_POWERED | USB_CONFIG_REMOTE_WAKEUP), /* bmAttribute */
        0x32 /* bMaxPower  */
},

{
//Standard Interface Descriptor
        sizeof(USB_STD_IF_DESC), /* bLength */
        USB_TYPE_INTERFACE_DESC, /* bDescriptorType */
        0x00, /* bInterfaceNumber */
        0x00, /* bAlternateSetting */
        NUM_OF_ENDPOINT, /* bNumEndPoints */
        0xFF, /* bInterfaceClass */
        0x00, /* bInterfaceSubClass */
        0xFF, /* bInterfaceProtocol */
        0x00 /* iInterface */
},

{
//Bulk In Endpoint Descriptor
        sizeof(USB_STD_EP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
        0x81, /* bEndpointAddress */
        USB_EP_BULK, /* bmAttribute  */
        0x040, /* wMaxPacketSize */
        0x01 /* bInterval */
},

{
//Bulk Out Endpoint Descriptor
        sizeof(USB_STD_EP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
        0x01, /* bEndpointAddress */
        USB_EP_BULK, /* bmAttribute  */
        0x040, /* wMaxPacketSize */
        0x01 /* bInterval */
}};

/**
 *  @brief String Descriptor Data.
 */
static uint8_t string_desc[6][128] = {"Language ID", "Lattice Semiconductor",
        "Lattice USB23", "00000001", "Config 1", "Default Interface"};

/**
 *  @brief BOS Descriptor Data.
 */
LSC_USB_BOS_DESC __attribute__ ((aligned(4))) bos_desc = {{
//BOS descriptor
        sizeof(USB_STD_BOS_DESC), /* bLength */
        USB_TYPE_BOS_DESC, /* DescriptorType */
        sizeof(LSC_USB_BOS_DESC), /* wTotalLength */
        0x03 /* bNumDeviceCaps */
},

{
//USB20 Device Ext Capability descriptor
        sizeof(USB_STD_U20_DEVICE_EXT_DESC), /* bLength */
        USB_DEVICE_CAPABILITY_TYPE, /* bDescriptorType */
        USB20_EXT_DESC, /* bDevCapabiltyType */
#ifdef LSC_LPM_ENABLE
        0x06, 0x0, 0x0, 0x0 /* bmAttributes */
#else
        0x0, 0x0, 0x0, 0x0 /* Disable LPM/BESL for USB 2.0*/
#endif
},

{
//Super Speed Device Capability descriptor
        sizeof(USB_STD_SS_DEVICE_CAP_DESC), /* bLength */
        USB_DEVICE_CAPABILITY_TYPE, /* bDescriptorType */
        SS_DEV_CAP_DESC, /* bDevCapabiltyType */
        0x00, /* bmAttributes */
        0x000E, /* wSpeedsSupported */
        0x02, /* bFunctionalitySupport */
#ifdef LSC_U1_U2
        0x03, /* bU1DevExitLat */
        0x00ff /* wU2DevExitLat */
#else
        0x0, /* Disable LPM for USB 3.0 */
        0x00
#endif
},

{
//Platform Capability descriptor
        (sizeof(USB_STD_PLATFORM_CAP_DESC)), /* bLength */
        USB_DEVICE_CAPABILITY_TYPE, /* bDescriptorType */
        PLATFORM_CAP_DESC, /*bDevCapabilityType*/
        0x00, /*bReserved*/
        0xDF, 0x60, 0xDD, 0xD8,  // MS_OS_20_Platform_Capability_ID -
        0x89, 0x45, 0xC7, 0x4C, // {D8DD60DF-4589-4CC7-9CD2-659D9E648A9F}
        0x9C, 0xD2, 0x65, 0x9D,  //
        0x9E, 0x64, 0x8A, 0x9F,  //
        /* CapabilityData  */
        0x00, 0x00, 0x03, 0x06, /* dwWindowsVersion  */
        0x4A, 0x01, /* wMSOSDescriptorSetTotalLength - 0x14A */
        WINUSB_REQ, /* bMS_VendorCode  */
        0x00 /* bAltEnumCode  */
}};

/**
 *  @brief USB20 UVC High Speed YUY2 Bulk Configuration Descriptor Data.
 */
LSC_YUY2_BULK_CFG_DESC_HS __attribute__ ((aligned(4))) yuy2_bulk_cfg_desc_hs = {{
//Standard Configuration Descriptor
        sizeof(USB_STD_CFG_DESC),
        USB_TYPE_CONFIG_DESC,
        sizeof(LSC_YUY2_BULK_CFG_DESC_HS),
        0x02,/* bNumInterfaces */
        0x01,/* bConfigurationValue */
        0x00,/* iConfiguration */
        0xC0,/* bmAttributes */
        0x32/* bMaxPower */
},

{
//Standard Interface Association DescriptorDescriptor
        sizeof(USB_STD_IAD),
        USB_TYPE_INTERFACE_ASSOCIATION,
        0x00,
        0x02,
        CC_VIDEO,
        SC_VIDEO_INTERFACE_COLLECTION,
        PC_PROTOCOL_UNDEFINED,
        0x02
},

{
//Standard Interface Descriptor (Video Control Interface)
        sizeof(USB_STD_IF_DESC),
        USB_TYPE_INTERFACE_DESC,
        0x00,
        0x00,
        NO_OF_EP_INTERFACE_DESC_BULK,
        CC_VIDEO ,
        SC_VIDEOCONTROL,
        PC_PROTOCOL_VAL,
        0x02
},

{
//Class Specific Video Control Interface Descriptor
        sizeof(USB_UVC_VCID),
        CS_INTERFACE,
        VC_HEADER,
        BCD_UVC,
        VCID_TOTAL_LEN,
        DEV_CLK_FREQ,
        0x01,
        {0x01}
},

{
//Input Terminal Descriptor (Camera)
        sizeof(USB_UVC_CTD),
        CS_INTERFACE,
        VC_INPUT_TERMINAL,
        0x01,
        ITT_CAMERA,
        0x02,
        0x00,
        0x00,
        0x00,
        0x00,
        NO_OF_CAMERA_CONTROLS_SUPPORTED,
        CTD_BM_CTRLS
},

{
//Output Terminal Descriptor
        sizeof(USB_UVC_OTD),
        CS_INTERFACE,
        VC_OUTPUT_TERMINAL,
        0x02,
        TT_STREAMING,
        0x01,
        0x01,
        0x00
},

//{
////Processing Unit Descriptor
//        sizeof(USB_UVC_PUD),
//        CS_INTERFACE,
//        VC_PROCESSING_UNIT,
//        PU_0_D_ID,
//        0x01,
//        0x00,
//        NO_OF_PROCESSING_UNIT_0_CONTROLS_SUPPORTED,
//        PU_D_BM_CTRLS,
//        0x00,
//        0x00
//},

{
//Extension Unit Descriptor
        sizeof(USB_UVC_XUD),
        CS_INTERFACE,
        VC_EXTENSION_UNIT,
        EU_D_ID,
        0x0c, 0x89, 0xb6, 0xac,
        0xb3, 0xa3, 0x60, 0x40,
        0x8b, 0x9a, 0xdf, 0x34,
        0xee, 0xf3, 0x9a, 0x2f,
        NO_OF_EXTENSION_UNIT_CONTROLS_SUPPORTED,
        NO_OF_EXTENSION_UNIT_INPUT_PINS_SUPPORTED,
        EU_D_SRC_ID,
        EXTENSION_UNIT_CONTROLS_SUPPORTED_SZ,
        EU_D_BM_CTRLS,
        0x00
},

#ifdef STILL_IMG_CAP
{
//Interrupt In Endpoint Descriptor
        sizeof(USB_STD_EP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
        0x82, /* bEndpointAddress */
        USB_EP_INTERRUPT, /* bmAttribute  */
        0x0008, /* wMaxPacketSize */
        0x0A, /* bInterval */
},

{
//Class Specific Interrupt In Endpoint Descriptor
        sizeof(USB_UVC_CS_INT_EP),
        CS_ENDPOINT,
        EP_INTERRUPT,
        0x0020
},
#endif

{
//Standard Interface Descriptor (Video Streaming Interface)
        sizeof(USB_STD_IF_DESC),
        USB_TYPE_INTERFACE_DESC,
        0x01,
        0x00,
        0x01,
        CC_VIDEO,
        SC_VIDEOSTREAMING,
        PC_PROTOCOL_VAL,
        0x00
},

{
//Class Specific VS Input Header Descriptor
        sizeof(USB_UVC_VSIHD),
        CS_INTERFACE,
        VS_INPUT_HEADER,
        NO_OF_FORMATS_SUPPORTED_BY_VIDEO_STREAM_INTERFACE,
        VSI_IHD_TOTAL_LEN,
        0x81,
        0x00,
        0x02,
        STILL_IMG_CAP_METHOD,
        TRIGGER_SUPPORT,
        0x00,
        0x01,
        {0x00}
},

#ifdef UVC_YUY2
{
//Uncompressed Video Format Descriptor
        sizeof(USB_UVC_UVFD),
        CS_INTERFACE,
        VS_FORMAT_UNCOMPRESSED,
        0x01,
        0x02, //adding second framed descriptor for 720p/1080p selection
        YUY2_GUID,
        BITSPERPIXEL,
        0x02,  // bDefaultFrameIndex: Changed from 0x01 (1080p) to 0x02 (720p)
        0x00,
        0x00,
        0x00
},

{
//Uncompressed Video Continues Frame Descriptor
        sizeof(USB_UVC_UVCFD),
        CS_INTERFACE,
        VS_FRAME_UNCOMPRESSED,
        FRAME_INDEX_1920x1080,
        UVCFD_CAPABILITIES,
        0x0780, //1920 width
        0x0438, //1080 height
        MAXBITRATE,
        MINBITRATE,
        (((1920*1080*BITSPERPIXEL)/8)+2),
        DEFAULTFRAMEINTERVAL,
        UVCFD_FRAMEINTERVALTYPE,
        MINIMUMFRAMEINTERVAL,
        (MINIMUMFRAMEINTERVAL + FRAMEINTERVALSTEP),
        FRAMEINTERVALSTEP
},
{
//Uncompressed Video Continues Frame Descriptor (1280x720)
        sizeof(USB_UVC_UVCFD),
        CS_INTERFACE,
        VS_FRAME_UNCOMPRESSED,
        FRAME_INDEX_1280x720,  // Frame Index 0x02
        UVCFD_CAPABILITIES,
        0x0500,  // 1280 width
        0x02D0,  // 720 height
        MAXBITRATE,
        MINBITRATE,
        (((1280*720*BITSPERPIXEL)/8)+2),
        DEFAULTFRAMEINTERVAL,
        UVCFD_FRAMEINTERVALTYPE,
        MINIMUMFRAMEINTERVAL,
        (MINIMUMFRAMEINTERVAL + FRAMEINTERVALSTEP),
        FRAMEINTERVALSTEP
},
#else
{
//MJPEG Video Format Descriptor
        sizeof(USB_UVC_MVFD),
        CS_INTERFACE,
        VS_FORMAT_MJPEG,
        0x01,
        0x01,
        0x01,
        0x01,
        0x00,
        0x00,
        0x00,
        0x00
},

{
//MJPEG Video Continues Frame Descriptor
        sizeof(USB_UVC_MVCFD),
        CS_INTERFACE,
        VS_FRAME_MJPEG,
        0x01,
        0x00,
        0x0780,/*height*/
        0x0438,/*width*/
        0x001A99A0,
        0x001B56C8,
        0x001C2002,
        0x00041FBE,
        0x00,
        0x00041FBE,
        0x00043D11,
        0x00000001
},
#endif

#ifdef STILL_IMG_CAP
{
//Class-specific Still Image Frame Descriptor
        sizeof(USB_UVC_SIFD),
        CS_INTERFACE,
        VS_STILL_IMAGE_FRAME,
        0x00,
        NO_OF_FRAMES_IN_STILL_IMAGE,
        {{0x0140,0xF0}},
        (NO_OF_FRAMES_IN_STILL_IMAGE-1)
},
#endif
{
//Class-specific Color Matching Descriptor
        sizeof(USB_UVC_CMD),\
        CS_INTERFACE,\
        VS_COLORFORMAT,\
        0x00,\
        0x00,\
        0x00\
},

{
//Standard VS Bulk In Endpoint Descriptor
        sizeof(USB_STD_EP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
        0x81, /* bEndpointAddress */
        USB_EP_BULK, /* bmAttribute  */
        EP_MAX_PKT_SIZE_512, /* wMaxPacketSize */
        0x00, /* bInterval */
}};

/**
 *  @brief USB20 UVC High Speed YUY2 Bulk Configuration Descriptor Data.
 */
LSC_YUY2_BULK_CFG_DESC_SS __attribute__ ((aligned(4))) yuy2_bulk_cfg_desc_ss = {{
//Standard Configuration Descriptor
        sizeof(USB_STD_CFG_DESC),
        USB_TYPE_CONFIG_DESC,
        sizeof(LSC_YUY2_BULK_CFG_DESC_SS),
        0x02,/* bNumInterfaces */
        0x01,/* bConfigurationValue */
        0x00,/* iConfiguration */
        0xC0,/* bmAttributes */
        0x32/* bMaxPower */
},

{
//Standard Interface Association DescriptorDescriptor
        sizeof(USB_STD_IAD),
        USB_TYPE_INTERFACE_ASSOCIATION,
        0x00,
        0x02,
        CC_VIDEO,
        SC_VIDEO_INTERFACE_COLLECTION,
        PC_PROTOCOL_UNDEFINED,
        0x02
},

{
//Standard Interface Descriptor (Video Control Interface)
        sizeof(USB_STD_IF_DESC),
        USB_TYPE_INTERFACE_DESC,
        0x00,
        0x00,
        NO_OF_EP_INTERFACE_DESC_BULK,
        CC_VIDEO ,
        SC_VIDEOCONTROL,
        PC_PROTOCOL_VAL,
        0x02
},

{
//Class Specific Video Control Interface Descriptor
        sizeof(USB_UVC_VCID),
        CS_INTERFACE,
        VC_HEADER,
        BCD_UVC,
        VCID_TOTAL_LEN,
        DEV_CLK_FREQ,
        0x01,
        {0x01}
},

{
//Input Terminal Descriptor (Camera)
        sizeof(USB_UVC_CTD),
        CS_INTERFACE,
        VC_INPUT_TERMINAL,
        0x01,
        ITT_CAMERA,
        0x02,
        0x00,
        0x00,
        0x00,
        0x00,
        NO_OF_CAMERA_CONTROLS_SUPPORTED,
        CTD_BM_CTRLS
},

{
//Output Terminal Descriptor
        sizeof(USB_UVC_OTD),
        CS_INTERFACE,
        VC_OUTPUT_TERMINAL,
        0x02,
        TT_STREAMING,
        0x01,
        0x01,
        0x00
},

//{
////Processing Unit Descriptor
//        sizeof(USB_UVC_PUD),
//        CS_INTERFACE,
//        VC_PROCESSING_UNIT,
//        PU_0_D_ID,
//        0x01,
//        0x00,
//        NO_OF_PROCESSING_UNIT_0_CONTROLS_SUPPORTED,
//        PU_D_BM_CTRLS,
//        0x00,
//        0x00
//},

{
//Extension Unit Descriptor
        sizeof(USB_UVC_XUD),
        CS_INTERFACE,
        VC_EXTENSION_UNIT,
        EU_D_ID,
        0x0c, 0x89, 0xb6, 0xac,
        0xb3, 0xa3, 0x60, 0x40,
        0x8b, 0x9a, 0xdf, 0x34,
        0xee, 0xf3, 0x9a, 0x2f,
        NO_OF_EXTENSION_UNIT_CONTROLS_SUPPORTED,
        NO_OF_EXTENSION_UNIT_INPUT_PINS_SUPPORTED,
        EU_D_SRC_ID,
        EXTENSION_UNIT_CONTROLS_SUPPORTED_SZ,
        EU_D_BM_CTRLS,
        0x00
},

#ifdef STILL_IMG_CAP
{
//Interrupt In Endpoint Descriptor
        sizeof(USB_STD_EP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
        0x82, /* bEndpointAddress */
        USB_EP_INTERRUPT, /* bmAttribute  */
        0x0008, /* wMaxPacketSize */
        0x0A, /* bInterval */
},
{
//Standard VS Bulk In SS Endpoint Companion Descriptor
        sizeof(USB_STD_EP_SS_COMP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CMP_DESC, /* bDescriptorType */
        0x0F, /* bMaxBurst */
        0x00, /* bmAttributes */
        0x0000, /*wBytesPerInterval*/
},
{
//Class Specific Interrupt In Endpoint Descriptor
        sizeof(USB_UVC_CS_INT_EP),
        CS_ENDPOINT,
        EP_INTERRUPT,
        0x0020
},
#endif

{
//Standard Interface Descriptor (Video Streaming Interface)
        sizeof(USB_STD_IF_DESC),
        USB_TYPE_INTERFACE_DESC,
        0x01,
        0x00,
        0x01,
        CC_VIDEO,
        SC_VIDEOSTREAMING,
        PC_PROTOCOL_VAL,
        0x00
},

{
//Class Specific VS Input Header Descriptor
        sizeof(USB_UVC_VSIHD),
        CS_INTERFACE,
        VS_INPUT_HEADER,
        NO_OF_FORMATS_SUPPORTED_BY_VIDEO_STREAM_INTERFACE,
        VSI_IHD_TOTAL_LEN,
        0x81,
        0x00,
        0x02,
        STILL_IMG_CAP_METHOD,
        TRIGGER_SUPPORT,
        0x00,
        0x01,
        {0x00}
},

#ifdef UVC_YUY2
{
//Uncompressed Video Format Descriptor
        sizeof(USB_UVC_UVFD),
        CS_INTERFACE,
        VS_FORMAT_UNCOMPRESSED,
        0x01,
        0x02,
        YUY2_GUID,
        BITSPERPIXEL,
        0x02,  // bDefaultFrameIndex: Changed from 0x01 (1080p) to 0x02 (720p)
        0x00,
        0x00,
        0x00
},

{
        //Uncompressed Video Continues Frame Descriptor
                sizeof(USB_UVC_UVCFD),
                CS_INTERFACE,
                VS_FRAME_UNCOMPRESSED,
                FRAME_INDEX_1920x1080,
                UVCFD_CAPABILITIES,
                0x0780, //1920 width
                0x0438, //1080 height
                MAXBITRATE,
                MINBITRATE,
                (((1920*1080*BITSPERPIXEL)/8)+2),
                DEFAULTFRAMEINTERVAL,
                UVCFD_FRAMEINTERVALTYPE,
                MINIMUMFRAMEINTERVAL,
                (MINIMUMFRAMEINTERVAL + FRAMEINTERVALSTEP),
                FRAMEINTERVALSTEP
        },
        {
        //Uncompressed Video Continues Frame Descriptor (1280x720)
                sizeof(USB_UVC_UVCFD),
                CS_INTERFACE,
                VS_FRAME_UNCOMPRESSED,
                FRAME_INDEX_1280x720,  // Frame Index 0x02
                UVCFD_CAPABILITIES,
                0x0500,  // 1280 width
                0x02D0,  // 720 height
                MAXBITRATE,
                MINBITRATE,
                (((1280*720*BITSPERPIXEL)/8)+2),
                DEFAULTFRAMEINTERVAL,
                UVCFD_FRAMEINTERVALTYPE,
                MINIMUMFRAMEINTERVAL,
                (MINIMUMFRAMEINTERVAL + FRAMEINTERVALSTEP),
                FRAMEINTERVALSTEP
        },
#else
{
//MJPEG Video Format Descriptor
        sizeof(USB_UVC_MVFD),
        CS_INTERFACE,
        VS_FORMAT_MJPEG,
        0x01,
        0x01,
        0x01,
        0x01,
        0x00,
        0x00,
        0x00,
        0x00
},

{
//MJPEG Video Continues Frame Descriptor
        sizeof(USB_UVC_MVCFD),
        CS_INTERFACE,
        VS_FRAME_MJPEG,
        0x01,
        0x00,
        0x0780,/*height*/
        0x0438,/*width*/
        0x001A99A0,
        0x001B56C8,
        0x001C2002,
        0x00041FBE,
        0x00,
        0x00041FBE,
        0x00043D11,
        0x00000001
},
#endif

#ifdef STILL_IMG_CAP
{
//Class-specific Still Image Frame Descriptor
        sizeof(USB_UVC_SIFD),
        CS_INTERFACE,
        VS_STILL_IMAGE_FRAME,
        0x00,
        NO_OF_FRAMES_IN_STILL_IMAGE,
        {{0x0280,0x1E0}},
        (NO_OF_FRAMES_IN_STILL_IMAGE-1)
},
#endif
{
//Class-specific Color Matching Descriptor
        sizeof(USB_UVC_CMD),\
        CS_INTERFACE,\
        VS_COLORFORMAT,\
        0x00,\
        0x00,\
        0x00\
},

{
//Standard VS Bulk In Endpoint Descriptor
        sizeof(USB_STD_EP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CFG_DESC, /* bDescriptorType */
        0x81, /* bEndpointAddress */
        USB_EP_BULK, /* bmAttribute  */
        EP_MAX_PKT_SIZE_1024, /* wMaxPacketSize */
        0x00, /* bInterval */
},
{
//Standard VS Bulk In SS Endpoint Companion Descriptor
        sizeof(USB_STD_EP_SS_COMP_DESC), /* bLength */
        USB_TYPE_ENDPOINT_CMP_DESC, /* bDescriptorType */
        0x0F, /* bMaxBurst */
        0x00, /* bmAttributes */
        0x0000, /*wBytesPerInterval*/
}};

#ifdef __cplusplus
}
#endif

#endif /* LSC_USB_DESC_H_ */

/** @} */
