
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.0.0
    2026 03 21 22:32:19
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="usb_bus_interface_bridge", LATTICE_IP_GENERATED="1" *) module usb_bus_interface_bridge (lmmi_rdata_o, 
        lmmi_rdata_valid_o, 
        lmmi_ready_o, 
        lmmi_request_i, 
        lmmi_wr_rdn_i, 
        lmmi_offset_i, 
        lmmi_wdata_i, 
        LMMIRDATA, 
        LMMIRDATAVALID, 
        LMMIREADY, 
        LMMIREQUEST, 
        LMMIWRRD_N, 
        LMMIOFFSET, 
        LMMIWDATA, 
        INTERRUPT, 
        RISCV_USB_INTERRUPT) ;
    output [31:0] lmmi_rdata_o ; 
    output lmmi_rdata_valid_o ; 
    output lmmi_ready_o ; 
    input lmmi_request_i ; 
    input lmmi_wr_rdn_i ; 
    input [14:0] lmmi_offset_i ; 
    input [31:0] lmmi_wdata_i ; 
    input [31:0] LMMIRDATA ; 
    input LMMIRDATAVALID ; 
    input LMMIREADY ; 
    output LMMIREQUEST ; 
    output LMMIWRRD_N ; 
    output [14:0] LMMIOFFSET ; 
    output [31:0] LMMIWDATA ; 
    input INTERRUPT ; 
    output RISCV_USB_INTERRUPT ; 
    usb_bus_interface_bridge_ipgen_usb23_bus_intf_bridge #(.ADDR_WIDTH_I(17),
            .DATA_WIDTH_I(32)) usb23_bus_intf_bridge_inst (.lmmi_rdata_o(lmmi_rdata_o[31:0]), 
                .lmmi_rdata_valid_o(lmmi_rdata_valid_o), 
                .lmmi_ready_o(lmmi_ready_o), 
                .lmmi_request_i(lmmi_request_i), 
                .lmmi_wr_rdn_i(lmmi_wr_rdn_i), 
                .lmmi_offset_i(lmmi_offset_i[14:0]), 
                .lmmi_wdata_i(lmmi_wdata_i[31:0]), 
                .LMMIRDATA(LMMIRDATA[31:0]), 
                .LMMIRDATAVALID(LMMIRDATAVALID), 
                .LMMIREADY(LMMIREADY), 
                .LMMIREQUEST(LMMIREQUEST), 
                .LMMIWRRD_N(LMMIWRRD_N), 
                .LMMIOFFSET(LMMIOFFSET[14:0]), 
                .LMMIWDATA(LMMIWDATA[31:0]), 
                .INTERRUPT(INTERRUPT), 
                .RISCV_USB_INTERRUPT(RISCV_USB_INTERRUPT)) ; 
endmodule



`pragma protect begin_protected

`pragma protect version=1
`pragma protect author="Lattice Semiconductor Corporation"
`pragma protect author_info="Lattice Semiconductor Corporation"
`pragma protect encrypt_agent="Radiant encrypt_hdl"
`pragma protect encrypt_agent_info="Radiant encrypt_hdl Version 1.0"

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Lattice Semiconductor"
`pragma protect key_keyname="LSCC_RADIANT_2"
`pragma protect key_method="rsa"
`pragma protect key_block
b+NZPqzzL9vwsSJNkLR2U33mtwcewUEWkoeyVohonWuphdLQFqWgBGTr7w2FY/UX
abkY1nPPPdmLpYDEfmvr0NQ4COlPwn1ZRssG4we/z6WO0pw1q2TyHcWFUxQUfeKx
Jbue0E+j1F0xyzieetCkfeIzg8LWmXzj/yCV55TX7aY3McKvJGYlWRmhd7HXr7s2
ELS0NQsdqNZbZME9reHTmgYWgB0yKPZcvGWtbK/nFk1RsTq9Wm29k6d2TPdzP29T
rZOypCjzQb1Ny3csfkg18+ikobS/L7AhNAfgA/NaCdnlLaCOg6z7BTJjZy1YUE8E
OtoRnQZguKKLlQXyt8x5MQ==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Synplicity"
`pragma protect key_keyname="SYNP15_1"
`pragma protect key_method="rsa"
`pragma protect key_block
X0B9o8YGF3HB3/KYgY+novja8r6gj8xwueQ99e+iMmGYNltbjZgQ6GS8hybsdOFD
lfks2mSYD+2El3XGvsFa53cem1kP5wSvvpo5pLtWzGGF2SmgL8+YWrEF7fgADjfS
A8MYZoK2BkuyWE/K5CB2zBgoaxWuSib3xiWQ/Bg/z5Qh5jQc4KR/pLfBPJ3mWHAm
0eMU9H6UqWjI28EIZVH5l/rj7+R11z0sSzCht+7iyn24JD5eBsxw2p5Fn0Kao97b
rhpiG4dAjS5vhYY0cM5XjYf03QNRYpg26g7Y1qAsNeJHoYbZIQt+wtidiMItBcCA
vNzAgiunOKx+sxAztsHVzQ==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Synplicity"
`pragma protect key_keyname="SYNP05_001"
`pragma protect key_method="rsa"
`pragma protect key_block
wjVcz7gEOc3VsGUgVM7cs2W2h6jFduxlXqA1i6hJIb/bJJ4zqiu3w5bT+jAqpI+9
9k1ykp+YtiZWybQfSPv/tO+QsuXmk+4Dh9P8WWQCUQx52GdvCRD7kBzukJr4w/Vt
Zw3GEorMiIEdyiscSvlQ3AT+VNSh0IRjDfcAOg/rr56P14+F0VqdZ1h0lHhqbRZj
NmcpoNoJDv/r2RQhMTCN9xVaRSVNwRV6NEsqDCQF1rl4XYnVDdr9v4hzAYXYQfMM
/m7GK1LCdqoxzKZ8+8PuR6R01SNGYm/fn3E59KFbb8pLI5UIyXslUOjZ92rpQp17
GV5Uck7J9IBB42GlUoZa/Q==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Mentor Graphics Corporation"
`pragma protect key_keyname="MGC-VERIF-SIM-RSA-2"
`pragma protect key_method="rsa"
`pragma protect key_block
SglWmDslaAEiEOXNsmsKb4TrbKB4LLr1/ajks67ertfwq8XtqUkDwgkU17rbuCVg
TE/Wy8NUujK85KyJplW2OHzh9/z+IUHs+brGQj+K6waWsUjPY6rHcvehlJo/EDYi
k9PAuSjtNFVFpADRaQYymMRDH5CZbBb5C1FhHMAhHtZ/PSxYviUAa2YPcR+wEL0+
Hk8zPJbq/V4psu94Kw96nQUcA1Cxncn2kTKizQah2SyWxxBy/5r1XWuu11LxVOT3
MYiKn9KCctWgUQezPznF8/Zsi9baRmp6i4RVd7xt+zUNANccekuSsCF7JBkZrn/9
vu/bTIc/fT49DRPGhsubew==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=128)
`pragma protect key_keyowner="Synopsys"
`pragma protect key_keyname="SNPS-VCS-RSA-1"
`pragma protect key_method="rsa"
`pragma protect key_block
0r5GTKd9rJ5OYQ01KnSS2P9aDWtD67Ht14QHLBlYqgR2S0knKopSK2ilDC96MuSf
bWK/j1NnfAS2W8yJ7s8ZDsAgVe/CCmowXZaaSmYCa36n4B/UyFDdw/Yvjlkh8jos
KrSSa3v9/eW21khFJgJR8PVomDBJCfNjOqzW4XOIftU=

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Aldec"
`pragma protect key_keyname="ALDEC15_001"
`pragma protect key_method="rsa"
`pragma protect key_block
XaHsaCR2Upz2ZHuUDvEzerfIQRAtfSNcLRYL1ONvxj1S7IAjUoP3xb4Kh0TzD4ek
O/m6OAS0Ycv3nPDeKjNjv/i42aaSGmOBZcqRX+ke4IK2SdR4+BR5IZKZbogT8Wrl
7wglA4IuvKMDZyhRD6D+MlGolk0OFMs+NMvGNNE4IEZJosc7AD0td167b0UXR4p9
rizCyOr+aGdcG1wqRBU2jQZaH1SBuydsuApJwesoSDxCqxYguhYQ/93TjXwCc1YY
e67bdqAlqUR47j2hevH5H2+xXr5uZMoyYUP8HB5ACo6VEuiuoHmjbNbyNwsbgRvI
L8xdT4j8EejIHzF0OUX54A==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=256)
`pragma protect key_keyowner="Cadence Design Systems."
`pragma protect key_keyname="CDS_RSA_KEY_VER_1"
`pragma protect key_method="rsa"
`pragma protect key_block
nWhlMogXChPLsavXJK3SIdK2DvGIC8QOOi6UMV4dytOw0Jjfyn14uGVHK4dk7Qbn
+KmGL967kDS+JqkJA64pnZEZa9oKNHgqfnnQtnLJhdGm0nGvwgG/MTfmpopmr7yQ
t4ybpqC5m4tbssuhlzLx+wC4/TzXNmp+aT+YsdXHJZwjgiwFECoYW3xBeWPTiS7F
ykPhMpKputXedldK7Lr3tn4wLAXTFiX5gNva9aa+GibuD0f1F6e6M97k7g+sSiDb
NLNyZ93+mQ0ySqJbWdC3eVm1FENmAaW4tm259oro9uxn9HX/Lx3BhlQ7XODVi+TY
kyLdvvh+SWFDOteNBIGlDA==

`pragma protect encoding=(enctype="base64", line_length=64, bytes=384)
`pragma protect key_keyowner="Lattice Semiconductor"
`pragma protect key_keyname="LSCC_RADIANT_3"
`pragma protect key_method="rsa"
`pragma protect key_block
UshUIj9qr0ko5Usrr0yKwHib+gkD0Z2zmhLf3d9GsEp5PnVOB1rvTL/LnBh5VpF6
LY2wv1Jc1fbY07Uxa6XO3iG2kBbStspMe7B0pcawwCxRjf7QSyHkfP516UHxnhm6
AVY4+E87dQ4OsdlzK5CZdcazSWFT5cUvdd3QE4t5PxUTw6FnisJWTwAPWpJM+SLb
eS3GW/yrsL5M6AKyJILKhv3l4Zef/mfeeTiy/2FfCOtmCOHPNI9nM19ZHuYcj8cH
DaohLBtHj+ktDpKlJL+zLodAEY+tRR84p9yQHpdZOiX6jub4qqrIzJNdZn9nIwHL
fjQy8QruLXaC+OwGmQTFeh/1ezuMRFEQGLLGYLnjGQ/SdExHUq5luNSsASH/G5lr
pjfpeyf5fxyEma9jYo0qlhXHwIQcvs38wxhpwhOO08N9kVn3cbQ3l7ey2COBAHWK
jrVTWcVpPuNn0iCec01dukzJ0a0/K9pwEQ1e5X6R6129JynuUSaE4qwOije5EE2F

`pragma protect data_method="aes256-cbc"
`pragma protect encoding=(enctype="base64", line_length=64, bytes=2080)
`pragma protect data_block
gdKbTnIFzRo8ZJcBRu+XrN4GMn6EXdnWPZ/C3MqpXiiaxj4bdpzofiSDntdkuFi7
NashqatHu61yjiqpAxlRzZ7JTaakl/h0qWqrDeXNTnnmnCel0ELbHOz6G0x0SYI8
6xCkf4A4pAafQaS/QNYwk0AWQzT5/IT7aIhx2PhX9JyXZopF7OV8TNfmAexjezEO
vEL8bFyG6uEiOQ7Y5kPFyfjf5/uEEZxz4ey/NnOeIucoLf0Or5mafz4xoR8imPMs
pSl3m/CDYuZdEiIf01181Qn2/i7rHYGwPygfdAmn9TmfbEwRGJ6Oj9RdYTgUMuAH
jA796s6JxfzaWt/FCojQQkHI6abuHoTXXSwh7vzjt2qlIymCXBVrVK7/aQiPDsaS
oNIzMHwHYUHqXZGt9pb6WRIh8BVQmdNOoYCrYh6s5wU7M2nXz7DkJTNJw+JRtkRb
SnPby676kuldXquCfLnqj4514m7EfcasCJWL5Nj+YYk4Lqr/NBlwjRiMfUS2YWQ9
j0PkSsiL+myeoLsN97L5h+mQQFROjMO8nhnJLXUdMuq4u9p7dO3vOIy97costZxe
TsoyS90W5lB+gc6ptHhS/leg0UfgQav/vYHr2nBmLdjybUKRsb4S3c6D9WkFDznI
Cl1CxQg8d5Bp7lCYttBU7tQQ6Px6WrJtQeElgzHGq/W0dKasD4dizvgxSDtDAJnD
YrAoUsyrLKa/jN28MOK7+tyCZqmXuFxQsZgWaPXHXRdy0PWvs3o3qc/urn1B8EwV
NA+dNudDk/bZigqtMpXdTntjD9+J7TfEoTWF19GHA3q6JPTnd++c5rm5ki0yxN6d
zWgaPz1nLbGSOBC79GrgBuJv9+CRO/rkfWOFS492bjS+J4Ymh+kcsTsMxxeP6+Z3
CmhHPBGhI/Y6lC1NleI9IQXxz7WM9SNYb+Ig6pP2vrLB6QSFbkw0WXrNYkRlsxVx
HN7TpZKLjLJM+Dy86es/76Z/BA7ouoIVIlQIhn+Pdx+NEiS+1e2GKDDa2eI/C47d
NaNxV5c3uhzrriR5IR7aBKnOqFExJjIiQchQ+Q+qpojeF1p+dBZXaJsZJoCDZmtV
ucgCsLA6bdWhfDJCTrw6VgiShRC/YA7mYVVPVeaVWQnDOFXLW6mTp8LwaxCQrSuJ
LCaf296tUvsv1bjq7EA01GZcYwSTFnnh85WF2RatP3jEeoFWTyFgA4qZNqpb0DSq
kby8i15EUxofv/42e5kX4AiIV9g4i8YFDV/yqah3wNROiHQ1DivkfV5hPYCxqHPM
V3eYstfKqEtS5AcN2Sx6ajv5v07bxLW9yItX4kIrmrowPQB1egSNGBKIrW8vDDIj
9NpzCkjDqxIVyb3hwSOYjavd30a4GJBXIFz4VwLgQrNtGdh59lSyuR7RtV07PNkH
sD9p4jrWdVS3X5kdott6kv5/5YTBzZKz0ArdeoyHUrvxXI1dsQ70eC3j8qqDmGUB
vnhbpQc34GWZDhrVH2jxMElB9gZY76ZHg7oO60K8Dj5Yh+uE6zBq+h+/EspD7Oa/
ogo+2EmtICvpm1hZteVEF1CdiAVL6jLUsyaZY4Bi5ecbhuhiPf7pD5jeA7OTi8VV
Y+0qpfUurWJOhd6wnVb3uJ3I03NtKGbJD1YbLx1cH5gJdPAZhIzUTx+HO/epOyp9
+NNiooCi87wIfiSSL7tWWmRNz4cL29aAKzaNpdsZaiux9uNZKxtao66dbNQZvhUI
6R1Ur7nRHqqVY73d4ufl0PcnxEGW46UBw6Vtu3LgbzQ0IqUew72UpAoE2gk8FQei
EHwGKu0cotKZoP2aNI4uVPwPxPOanM0vuFluGJbIObXImTxYX0kZDqlty2D2S3nV
gSu084RBWrjGygO0o6Iir2R8vZ7OoGvoDq0zaZWjr1nho9qutOHysT4ipaAUsw59
pAFJ/nkoWTgqFwa33fTWCx4e+Vhx/PzamUzuycUGbVbv5GFMhdWQDnKgHSh4PkDy
7ziWHCDVu3k2EkeO4NEHcGMmfrECsMCU7IQXGJ6vwHR0z50pyCntX+YtJLxTp1ue
5YMyLhhTHPVEekM+hbSzCPwfcxA/xgAqg6anDJrv1zwjifYLfAIrQ+hCfvfISZ18
QAzZgYVmyYI31IEfzOX9EJpZluwd9pMjcIiogdpioZ1zWIDaj/NlyFVoN1i0+wtC
uOupcdRjVdkpAEkA7e4/hDbFkgWxpRvfkKgJjua6/nUWHQ5NpK+tNeNLrvtkTQLT
/ovoY9e24moDcf0m/LMxMj7epX4Ccf0CY8SXw9hesFLqD9VA0Vz5enDfWve7VMky
JvCOjRrY8oJLcnTvoh5cTyOSjVwdZhhus0W/hU8uvvTMSvm8HY01ScxcU3nO4bGL
1tXEPASLlGk52zfWaTTczi7VQFfWbJ8WV1i2/p/88pOeO3SerbMHPFWB7eJR+PLT
SMhtTgSGBUE02DJb6q1uQqLny+muEz7YIe30UO9ikBVC1bluHu/u3IzPqJ4i2QpX
atoU1ibbEogzSvFmFG+8za5exjXyGaDCMqTjOuoEos0k4md556GIGabPa7ugrk8n
2HoOF/U0ckktzdVqIcT/K4a6ku/Jo+Uqd9x2vPpUOBvlAeSqvkxY4J4SalEwWcLZ
M1iMz8FGKq1/nDKbQcqSM5dVsZN4qBD8b4HdTF2RyOwoDts/mQQUyfA26SKIGC74
OqlrufNz4jV8BgQ005IBbb9GRy703ldns8RsZXqOA0XPc3/vrYL/65ihOe0X2OyH
7FrrXWytOTmmjVeYyTxyRA==

`pragma protect end_protected

