/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.0.0
    2026 03 21 22:32:19
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module usb_bus_interface_bridge (lmmi_rdata_o, lmmi_rdata_valid_o,
    lmmi_ready_o, lmmi_request_i, lmmi_wr_rdn_i, lmmi_offset_i, lmmi_wdata_i,
    LMMIRDATA, LMMIRDATAVALID, LMMIREADY, LMMIREQUEST, LMMIWRRD_N, LMMIOFFSET,
    LMMIWDATA, INTERRUPT, RISCV_USB_INTERRUPT)/* synthesis syn_black_box syn_declare_black_box=1 */;
    output  [31:0]  lmmi_rdata_o;
    output  lmmi_rdata_valid_o;
    output  lmmi_ready_o;
    input  lmmi_request_i;
    input  lmmi_wr_rdn_i;
    input  [14:0]  lmmi_offset_i;
    input  [31:0]  lmmi_wdata_i;
    input  [31:0]  LMMIRDATA;
    input  LMMIRDATAVALID;
    input  LMMIREADY;
    output  LMMIREQUEST;
    output  LMMIWRRD_N;
    output  [14:0]  LMMIOFFSET;
    output  [31:0]  LMMIWDATA;
    input  INTERRUPT;
    output  RISCV_USB_INTERRUPT;
endmodule