/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 1.0.0
    2026 04 14 15:33:13
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module unified_video_to_usb (clk_pll_72m, mipi_byte_clk, mipi_byte_clk_resetn,
    pixel_clk, pixel_clk_reset_n, system_reset_n, tdata, tuser, tlast, tready,
    tvalid, yuy2_tp_en, risc_v_system_reset_n_72m, mem_to_ahbl_32_wr_en_b,
    mem_to_ahbl_32_wr_data_b, mem_to_ahbl_32_addr_b, mem_to_ahbl_32_ben_b,
    mem_to_ahbl_32_rd_data_b, u23_axim_XMAWADDR, u23_axim_XMAWBURST,
    u23_axim_XMAWID, u23_axim_XMAWLEN, u23_axim_XMAWPROT, u23_axim_XMAWSIZE,
    u23_axim_XMAWREADY, u23_axim_XMAWVALID, u23_axim_XMWDATA, u23_axim_XMWSTRB,
    u23_axim_XMWLAST, u23_axim_XMWREADY, u23_axim_XMWVALID, u23_axim_XMARADDR,
    u23_axim_XMARBURST, u23_axim_XMARID, u23_axim_XMARLEN, u23_axim_XMARPROT,
    u23_axim_XMARSIZE, u23_axim_XMARREADY, u23_axim_XMARVALID,
    u23_axim_XMRDATA, u23_axim_XMRID, u23_axim_XMRRESP, u23_axim_XMRLAST,
    u23_axim_XMRREADY, u23_axim_XMRVALID, u23_axim_XMBID, u23_axim_XMBRESP,
    u23_axim_XMBREADY, u23_axim_XMBVALID, ahbl_haddr_i, ahbl_hburst_i,
    ahbl_hmastlock_i, ahbl_hprot_i, ahbl_hready_i, ahbl_hsel_i, ahbl_hsize_i,
    ahbl_htrans_i, ahbl_hwdata_i, ahbl_hwrite_i, ahbl_hrdata_o,
    ahbl_hreadyout_o, ahbl_hresp_o, iebm_ri_irq_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_pll_72m;
    input  mipi_byte_clk;
    input  mipi_byte_clk_resetn;
    input  pixel_clk;
    input  pixel_clk_reset_n;
    input  system_reset_n;
    input  [31:0]  tdata;
    input  [1:0]  tuser;
    input  tlast;
    output  tready;
    input  tvalid;
    input  yuy2_tp_en;
    input  risc_v_system_reset_n_72m;
    input  mem_to_ahbl_32_wr_en_b;
    input  [31:0]  mem_to_ahbl_32_wr_data_b;
    input  [9:0]  mem_to_ahbl_32_addr_b;
    input  [3:0]  mem_to_ahbl_32_ben_b;
    output  [31:0]  mem_to_ahbl_32_rd_data_b;
    input  [31:0]  u23_axim_XMAWADDR;
    input  [1:0]  u23_axim_XMAWBURST;
    input  [7:0]  u23_axim_XMAWID;
    input  [7:0]  u23_axim_XMAWLEN;
    input  [2:0]  u23_axim_XMAWPROT;
    input  [2:0]  u23_axim_XMAWSIZE;
    output  u23_axim_XMAWREADY;
    input  u23_axim_XMAWVALID;
    input  [63:0]  u23_axim_XMWDATA;
    input  [7:0]  u23_axim_XMWSTRB;
    input  u23_axim_XMWLAST;
    output  u23_axim_XMWREADY;
    input  u23_axim_XMWVALID;
    input  [31:0]  u23_axim_XMARADDR;
    input  [1:0]  u23_axim_XMARBURST;
    input  [7:0]  u23_axim_XMARID;
    input  [7:0]  u23_axim_XMARLEN;
    input  [2:0]  u23_axim_XMARPROT;
    input  [2:0]  u23_axim_XMARSIZE;
    output  u23_axim_XMARREADY;
    input  u23_axim_XMARVALID;
    output  [63:0]  u23_axim_XMRDATA;
    output  [7:0]  u23_axim_XMRID;
    output  [1:0]  u23_axim_XMRRESP;
    output  u23_axim_XMRLAST;
    input  u23_axim_XMRREADY;
    output  u23_axim_XMRVALID;
    output  [7:0]  u23_axim_XMBID;
    output  [1:0]  u23_axim_XMBRESP;
    input  u23_axim_XMBREADY;
    output  u23_axim_XMBVALID;
    input  [7:0]  ahbl_haddr_i;
    input  [2:0]  ahbl_hburst_i;
    input  ahbl_hmastlock_i;
    input  [3:0]  ahbl_hprot_i;
    input  ahbl_hready_i;
    input  ahbl_hsel_i;
    input  [2:0]  ahbl_hsize_i;
    input  [1:0]  ahbl_htrans_i;
    input  [31:0]  ahbl_hwdata_i;
    input  ahbl_hwrite_i;
    output  [31:0]  ahbl_hrdata_o;
    output  ahbl_hreadyout_o;
    output  ahbl_hresp_o;
    output  iebm_ri_irq_o;
endmodule